import type { Locale } from "@/lib/i18n";

// LOC-01 / AUTH-04/05: draft staff instructions need human bilingual UAT before release.
export const staffSecurityCopy = {
  en: {
    eyebrow: "MSRC 2027 / local security preview",
    title: "Protect staff access.",
    intro: "Try authenticator setup and session checks with a synthetic identity. Live staff access and all operational workflows remain closed.",
    synthetic: "Synthetic identity · local test only",
    start: "Start synthetic staff session",
    participant: "Start synthetic participant session",
    restart: "Start a new synthetic session",
    waiting: "Checking the synthetic session…",
    pending: "Working…",
    sessionTitle: "Session assurance",
    active: "Session active",
    revoked: "Session revoked",
    expired: "Session expired",
    noSession: "No synthetic session",
    staff: "Synthetic staff",
    participantLabel: "Synthetic participant",
    assuranceLabel: "Second factor",
    missing: "Not verified",
    assured: "Authenticator verified",
    accessClosed: "Live privileged access remains closed.",
    absolute: "Absolute expiry",
    idle: "Idle expiry",
    setupTitle: "Set up your authenticator",
    setupIntro: "Use an authenticator app on your own device. Choose either setup method below, then enter the six-digit code from the app.",
    enroll: "Set up authenticator",
    qrTitle: "Scan the QR code",
    qrAlt: "Authenticator setup QR code. The same setup is available using the manual key below.",
    qrNote: "In your authenticator app, add an account and scan this code. Keep this setup private.",
    manualTitle: "Or enter the setup key manually",
    manualNote: "Choose a time-based account. Enter this key, use six digits and a 30-second interval. The account is labeled MSRC 2027 Synthetic.",
    keyLabel: "Manual setup key",
    secretNote: "This temporary key is shown only for synthetic setup. It is removed from this screen after verification or a browser reload.",
    setupUnavailable: "This setup key is no longer displayed. Use the authenticator you already configured, or start a new synthetic session to set it up again.",
    challengeTitle: "Verify your authenticator",
    challengeIntro: "Enter the current code from the authenticator account you already set up. If you just used a code, wait for the next code before trying again.",
    challenge: "Request a new challenge",
    codeLabel: "Six-digit authenticator code",
    codeHint: "Paste or type the code. Arabic and Latin digits are accepted. Codes are never saved in browser storage.",
    verify: "Verify code",
    codeValidation: "Enter a six-digit authenticator code.",
    confirmed: "Your synthetic authenticator is verified. Live privileged access remains closed.",
    participantNote: "Participant sessions do not provide staff assurance. Public pages are available without signing in.",
    checkAccess: "Check synthetic staff access",
    refresh: "Refresh synthetic token",
    reauthenticate: "Reauthenticate synthetic session",
    logout: "Log out synthetic session",
    retry: "Retry session check",
    recoveryTitle: "Lost your authenticator?",
    recoveryIntro: "Factor recovery is unavailable until the approver, operator and verified reset procedure are approved. A password reset cannot bypass staff MFA.",
    recovery: "Check recovery availability",
    policyTitle: "Configured session policy",
    participantPolicy: "Participants: 72 hours maximum from the original sign-in.",
    privilegedPolicy: "Staff: 30 minutes idle and 8 hours maximum from the original sign-in.",
    refreshPolicy: "Refreshing a token does not restart either absolute lifetime. Session expiry is enforced on the server.",
    unsetPolicy: "Recent-authentication age and timeout-warning lead remain unset. Sensitive actions stay closed.",
    emailPolicy: "Security notifications use test/console mode only. Live email, privacy, retention and data-location approvals remain pending.",
    scenarioTitle: "Synthetic revocation checks",
    scenarioNote: "These checks revoke only the current synthetic session. They do not change a managed account, grant or live factor.",
    suspend: "Simulate suspension",
    factorReset: "Simulate factor-reset revocation",
    messages: {
      started: "Synthetic session started. Staff assurance requires an authenticator.",
      enrolled: "Setup is ready. Enter the code from your authenticator to confirm it.",
      challenge_created: "A new challenge is ready. Enter the current authenticator code.",
      verified: "Authenticator verified for this synthetic session.",
      protected_allowed: "The synthetic staff check passed. Live privileged access remains closed.",
      refreshed: "Synthetic token refreshed. The original absolute expiry is unchanged.",
      logged_out: "Synthetic session logged out. Its previous session can no longer pass access checks.",
      suspended: "Synthetic session revoked by the suspension check.",
      factor_reset_revoked: "Synthetic assurance and sessions revoked. Live factor recovery remains unavailable.",
      reauthenticated: "A new synthetic session started. Verify the authenticator again for staff assurance.",
      no_session: "Start a synthetic session to continue.",
      session_revoked: "This session was revoked. Start a new synthetic session to continue.",
      session_expired: "This session has expired. Start a new synthetic session to continue.",
      mfa_required: "Staff access requires a verified authenticator. Complete setup or a new challenge.",
      challenge_required: "Request a new challenge before verifying a code.",
      invalid_code: "The code could not be verified. Check the app and try a fresh code.",
      challenge_expired: "The challenge expired. Request a new challenge and try again.",
      retry_limited: "Too many attempts. Wait briefly, then request a new challenge and try again.",
      recovery_unconfigured: "Factor recovery is closed. Its approver, operator and verified reset procedure remain pending.",
      factor_already_enrolled: "An authenticator is already set up. Request a new challenge instead.",
      unavailable: "The session check is unavailable. Your entered code remains here so you can retry.",
    },
  },
  ar: {
    eyebrow: "MSRC ٢٠٢٧ / معاينة أمنية محلية",
    title: "حماية وصول الفريق.",
    intro: "جرّب إعداد تطبيق المصادقة والتحقق من الجلسة بهوية مصطنعة. يظل وصول الفريق الفعلي وجميع مسارات العمل التشغيلية مغلقًا.",
    synthetic: "هوية مصطنعة · للاختبار المحلي فقط",
    start: "بدء جلسة فريق مصطنعة",
    participant: "بدء جلسة مشارك مصطنعة",
    restart: "بدء جلسة مصطنعة جديدة",
    waiting: "جارٍ التحقق من الجلسة المصطنعة…",
    pending: "جارٍ التنفيذ…",
    sessionTitle: "التحقق من الجلسة",
    active: "الجلسة نشطة",
    revoked: "أُلغيت الجلسة",
    expired: "انتهت الجلسة",
    noSession: "لا توجد جلسة مصطنعة",
    staff: "عضو فريق مصطنع",
    participantLabel: "مشارك مصطنع",
    assuranceLabel: "عامل المصادقة الثاني",
    missing: "لم يُتحقق منه",
    assured: "تم التحقق من تطبيق المصادقة",
    accessClosed: "يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
    absolute: "انتهاء المدة القصوى",
    idle: "انتهاء مهلة الخمول",
    setupTitle: "إعداد تطبيق المصادقة",
    setupIntro: "استخدم تطبيق مصادقة على جهازك الشخصي. اختر إحدى طريقتي الإعداد أدناه، ثم أدخل الرمز المكوّن من ستة أرقام من التطبيق.",
    enroll: "إعداد تطبيق المصادقة",
    qrTitle: "مسح رمز QR",
    qrAlt: "رمز QR لإعداد تطبيق المصادقة. يمكن إجراء الإعداد نفسه باستخدام المفتاح اليدوي أدناه.",
    qrNote: "أضف حسابًا في تطبيق المصادقة وامسح هذا الرمز. احتفظ بمعلومات الإعداد بسرية.",
    manualTitle: "أو إدخال مفتاح الإعداد يدويًا",
    manualNote: "اختر حسابًا يعتمد على الوقت. أدخل هذا المفتاح واختر ستة أرقام وفترة ٣٠ ثانية. اسم الحساب هو MSRC 2027 Synthetic.",
    keyLabel: "مفتاح الإعداد اليدوي",
    secretNote: "يُعرض هذا المفتاح المؤقت للإعداد المصطنع فقط. يُزال من الشاشة بعد التحقق أو إعادة تحميل المتصفح.",
    setupUnavailable: "لم يعد مفتاح الإعداد معروضًا. استخدم تطبيق المصادقة الذي أعددته، أو ابدأ جلسة مصطنعة جديدة لإعادة الإعداد.",
    challengeTitle: "التحقق من تطبيق المصادقة",
    challengeIntro: "أدخل الرمز الحالي من حساب المصادقة الذي أعددته. إذا استخدمت رمزًا للتو، انتظر الرمز التالي قبل المحاولة مجددًا.",
    challenge: "طلب تحقق جديد",
    codeLabel: "رمز المصادقة المكوّن من ستة أرقام",
    codeHint: "الصق الرمز أو اكتبه. تُقبل الأرقام العربية واللاتينية. لا تُحفظ الرموز في تخزين المتصفح.",
    verify: "التحقق من الرمز",
    codeValidation: "أدخل رمز مصادقة مكوّنًا من ستة أرقام.",
    confirmed: "تم التحقق من تطبيق المصادقة المصطنع. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
    participantNote: "جلسات المشاركين لا تمنح تحقق الفريق. يمكن تصفح الصفحات العامة دون تسجيل الدخول.",
    checkAccess: "التحقق من وصول الفريق المصطنع",
    refresh: "تحديث رمز الجلسة المصطنعة",
    reauthenticate: "إعادة المصادقة للجلسة المصطنعة",
    logout: "تسجيل الخروج من الجلسة المصطنعة",
    retry: "إعادة محاولة التحقق من الجلسة",
    recoveryTitle: "فقدت تطبيق المصادقة؟",
    recoveryIntro: "استعادة عامل المصادقة غير متاحة حتى اعتماد المسؤول عن الموافقة والمشغّل وإجراء إعادة الضبط الموثّق. لا يمكن لإعادة ضبط كلمة المرور تجاوز المصادقة الثنائية للفريق.",
    recovery: "التحقق من إتاحة الاستعادة",
    policyTitle: "سياسة الجلسات المحددة",
    participantPolicy: "المشاركون: ٧٢ ساعة كحد أقصى من تسجيل الدخول الأصلي.",
    privilegedPolicy: "الفريق: مهلة خمول ٣٠ دقيقة ومدة قصوى ٨ ساعات من تسجيل الدخول الأصلي.",
    refreshPolicy: "تحديث رمز الجلسة لا يبدأ مدة قصوى جديدة. يُفرض انتهاء الجلسة على الخادم.",
    unsetPolicy: "لم تُحدد مدة صلاحية المصادقة الحديثة أو توقيت التحذير قبل انتهاء الجلسة. تظل الإجراءات الحساسة مغلقة.",
    emailPolicy: "إشعارات الأمان في وضع الاختبار فقط. لا تزال موافقات البريد الفعلي والخصوصية والاحتفاظ بالبيانات ومواقعها معلّقة.",
    scenarioTitle: "اختبارات إلغاء مصطنعة",
    scenarioNote: "تلغي هذه الاختبارات الجلسة المصطنعة الحالية فقط. لا تغيّر حسابًا مُدارًا أو صلاحية أو عامل مصادقة فعليًا.",
    suspend: "محاكاة التعليق",
    factorReset: "محاكاة الإلغاء بعد إعادة ضبط العامل",
    messages: {
      started: "بدأت الجلسة المصطنعة. يتطلب التحقق من الفريق تطبيق مصادقة.",
      enrolled: "الإعداد جاهز. أدخل الرمز من تطبيق المصادقة لتأكيده.",
      challenge_created: "طلب تحقق جديد جاهز. أدخل الرمز الحالي من تطبيق المصادقة.",
      verified: "تم التحقق من تطبيق المصادقة لهذه الجلسة المصطنعة.",
      protected_allowed: "اجتاز اختبار وصول الفريق المصطنع. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
      refreshed: "تم تحديث رمز الجلسة المصطنعة. لم يتغير وقت انتهاء المدة القصوى الأصلي.",
      logged_out: "تم تسجيل الخروج من الجلسة المصطنعة. لم تعد جلستها السابقة تجتاز التحقق من الوصول.",
      suspended: "أُلغيت الجلسة المصطنعة بواسطة اختبار التعليق.",
      factor_reset_revoked: "أُلغي التحقق والجلسات المصطنعة. تظل استعادة عامل المصادقة الفعلي غير متاحة.",
      reauthenticated: "بدأت جلسة مصطنعة جديدة. تحقق من تطبيق المصادقة مجددًا للتحقق من الفريق.",
      no_session: "ابدأ جلسة مصطنعة للمتابعة.",
      session_revoked: "أُلغيت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      session_expired: "انتهت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      mfa_required: "يتطلب وصول الفريق تطبيق مصادقة تم التحقق منه. أكمل الإعداد أو اطلب تحققًا جديدًا.",
      challenge_required: "اطلب تحققًا جديدًا قبل التحقق من الرمز.",
      invalid_code: "تعذر التحقق من الرمز. راجع التطبيق وجرب رمزًا جديدًا.",
      challenge_expired: "انتهت مهلة التحقق. اطلب تحققًا جديدًا وحاول مجددًا.",
      retry_limited: "تجاوزت عدد المحاولات. انتظر قليلًا، ثم اطلب تحققًا جديدًا وحاول مجددًا.",
      recovery_unconfigured: "استعادة عامل المصادقة مغلقة. لا يزال المسؤول عن الموافقة والمشغّل وإجراء إعادة الضبط الموثّق غير محددين.",
      factor_already_enrolled: "تم إعداد تطبيق مصادقة بالفعل. اطلب تحققًا جديدًا بدلًا من الإعداد.",
      unavailable: "التحقق من الجلسة غير متاح. يبقى الرمز المدخل هنا لتتمكن من إعادة المحاولة.",
    },
  },
} satisfies Record<Locale, unknown>;

export type StaffSecurityMessage = keyof typeof staffSecurityCopy.en.messages;
