import type { Locale } from "@/lib/i18n";

// LOC-01 / AUTH-02/04/05: regular staff have an additional session email check;
// Super Admin phone MFA and participant email/phone verification stay distinct.
export const staffSecurityCopy = {
  en: {
    eyebrow: "MSRC 2027 / local security preview",
    title: "Verify access, step by step.",
    intro: "Participants verify email and phone without MFA. Regular staff use password sign-in followed by a fresh email code. Super Admins retain their SMS second factor. Try the flows with synthetic identities; live access remains closed.",
    synthetic: "Synthetic identities · local test only",
    simulation: "Password sign-in is simulated. No real password or phone number is collected, and no real SMS or email is sent.",
    start: "Simulate staff password sign-in",
    startSuperAdmin: "Simulate Super Admin password sign-in",
    participant: "Simulate participant password sign-in",
    restart: "Start a new synthetic session",
    pending: "Working…",
    sessionTitle: "Session and verification",
    active: "Session active",
    revoked: "Session revoked",
    expired: "Session expired",
    noSession: "No synthetic session",
    staff: "Synthetic staff",
    superAdminLabel: "Synthetic Super Admin",
    participantLabel: "Synthetic participant",
    passwordLabel: "Password sign-in",
    passwordVerified: "Simulated and complete",
    verificationTitle: "Account verification",
    emailLabel: "Email verification",
    phoneLabel: "Phone verification",
    verificationComplete: "Email and phone verified",
    verificationPending: "Email and phone verification required",
    emailPending: "Email verification required",
    phonePending: "Phone verification required",
    verifiedStatus: "Verified",
    missing: "Not verified",
    assuranceLabel: "Super Admin second factor",
    staffEmailLabel: "Additional staff email check",
    staffEmailAssured: "Email check passed for this session",
    participantAssuranceLabel: "Participant MFA",
    assured: "SMS second factor verified",
    participantAssurance: "MFA not required for participants",
    accessClosed: "Live privileged access and operational workflows remain closed.",
    absolute: "Absolute expiry",
    idle: "Idle expiry",
    setupTitle: "Super Admin SMS verification",
    setupIntro: "After the simulated password sign-in, confirm the synthetic phone with an SMS code. The preview puts a test message below and sends no real SMS.",
    enroll: "Create synthetic Super Admin SMS challenge",
    challengeTitle: "Enter the SMS code",
    challengeIntro: "Use the latest six-digit code in the synthetic SMS test inbox. Requesting a replacement invalidates the previous code.",
    challenge: "Request a new synthetic SMS code",
    codeLabel: "Six-digit SMS code",
    codeHint: "Paste or type the latest test code. Arabic and Latin digits are accepted. Codes are never saved in browser storage.",
    verify: "Verify SMS code",
    codeValidation: "Enter a six-digit verification code.",
    confirmed: "Password and SMS checks passed for this synthetic Super Admin session. Live privileged access remains closed.",
    staffEmailTitle: "Complete the staff email check",
    staffEmailIntro: "After password sign-in, request a fresh code at the account’s verified email address. In this local preview the message appears in the test inbox; no email is sent.",
    staffEmailScope: "The code expires after five minutes. This additional check belongs to this login session and is not Supabase MFA or AAL2. A new login requires a fresh check; refreshing a token does not.",
    staffEmailCodeLabel: "Six-digit staff email code",
    staffEmailConfirmed: "Password and the additional email check passed for this synthetic staff session. Live staff access remains closed.",
    staffEmailExpired: "This email code has expired. Request a new code to continue.",
    staffEmailDeliveryFailed: "The email code could not be requested. Wait, then try again. Your entered code remains here; staff access is still closed.",
    staffEmailRetryLimited: "Too many incorrect codes or requests. Five incorrect entries pause the email check for 15 minutes. Send limits may require a longer wait. Wait, then request a new code.",
    emailResendWait: "You can request another email code after",
    participantNote: "Participants continue using email and password to sign in. Email and phone verification are required for the account; they do not add MFA or staff access.",
    participantChecksPassed: "The synthetic participant account has both required verification checks. Its session remains AAL1 and no MFA factor is enrolled.",
    emailTitle: "Verify the participant email",
    emailIntro: "Create a synthetic email message, then enter its code. No real email is sent.",
    emailChallenge: "Request a synthetic email code",
    emailCodeLabel: "Six-digit email verification code",
    emailVerify: "Verify email code",
    phoneTitle: "Verify the participant phone",
    phoneIntro: "Create a synthetic SMS message, then enter its code. Phone verification does not grant participant MFA or staff access.",
    phoneCodeLabel: "Six-digit phone verification code",
    phoneVerify: "Verify participant phone",
    inboxTitle: "Synthetic test inbox",
    inboxNote: "Local test messages only. Nothing is sent to a phone or email address. Codes disappear after verification, sign-out or browser reload.",
    smsMessage: "Synthetic SMS message",
    emailMessage: "Synthetic email message",
    smsDestination: "Synthetic phone",
    emailDestination: "Synthetic email",
    messageCode: "Test verification code",
    messageExpiry: "Code expiry",
    messageDelivery: "Test-only delivery",
    checkAccess: "Check synthetic staff access",
    checkParticipant: "Check synthetic participant verification",
    refresh: "Refresh synthetic token",
    reauthenticate: "Simulate password reauthentication",
    logout: "Log out synthetic session",
    retry: "Retry session check",
    recoveryTitle: "Lost access to your email or phone?",
    recoveryIntro: "Recovery remains closed. In-person identity review and distinct Super Admin approval and reset roles are required; named custodians and email recovery details remain pending. Password recovery cannot bypass the required staff email check or Super Admin second factor.",
    recovery: "Check recovery availability",
    policyTitle: "Configured session policy",
    participantPolicy: "Participants: 72 hours maximum from the original sign-in.",
    privilegedPolicy: "Staff: 30 minutes idle and 8 hours maximum from the original sign-in.",
    refreshPolicy: "Refreshing a token does not restart either absolute lifetime. Session expiry is enforced on the server.",
    unsetPolicy: "Recent-authentication age and timeout-warning lead remain unset. Sensitive actions stay closed.",
    emailPolicy: "Production email delivery is unconfigured. Email messages stay English-only. SMS delivery, privacy, retention and data-location approvals remain pending. This preview uses test messages only.",
    scenarioTitle: "Synthetic revocation checks",
    scenarioNote: "These checks revoke only the current synthetic session. They do not change a managed account, grant, phone or live factor.",
    suspend: "Simulate suspension",
    factorReset: "Simulate factor-reset revocation",
    emailChange: "Simulate verified-email change",
    roleRevocation: "Simulate staff-role revocation",
    participantAllowed: "The synthetic participant verification check passed. Live operational access remains closed.",
    emailVerifiedPhonePending: "Synthetic participant email verified. Phone verification is still required.",
    participantReauthenticated: "A new simulated password session started. Participant verification status is retained; MFA is not required.",
    staffReauthenticated: "A new simulated password session started. Regular staff must complete a fresh email check.",
    messages: {
      started: "Synthetic password sign-in completed. Continue with the verification checks for this identity.",
      enrolled: "A synthetic Super Admin SMS challenge is ready in the test inbox. No real SMS was sent.",
      challenge_created: "A new synthetic SMS code is ready. The previous code is invalid.",
      email_challenge_created: "A synthetic email code is ready in the test inbox. No real email was sent.",
      verified: "SMS second factor verified for this synthetic Super Admin session.",
      staff_email_verified: "The additional email check passed for this synthetic staff session. Live staff access remains closed.",
      phone_verified: "Synthetic participant phone verified. Participant MFA remains unnecessary.",
      email_verified: "Synthetic participant email verified. Both account verification checks are complete.",
      protected_allowed: "The synthetic staff check passed. Live privileged access remains closed.",
      refreshed: "Synthetic token refreshed. The original absolute expiry is unchanged.",
      logged_out: "Synthetic session logged out. Its previous session can no longer pass access checks.",
      suspended: "Synthetic session revoked by the suspension check.",
      factor_reset_revoked: "Synthetic assurance and sessions revoked. Live factor recovery remains closed.",
      reauthenticated: "A new simulated password session started. Super Admins must verify a new SMS code.",
      no_session: "Start a synthetic session to continue.",
      session_revoked: "This session was revoked. Start a new synthetic session to continue.",
      session_expired: "This session has expired. Start a new synthetic session to continue.",
      mfa_required: "Super Admin access requires password sign-in and a verified SMS second factor.",
      staff_email_check_required: "Staff access requires password sign-in and a fresh email check for this session.",
      password_auth_required: "Complete password sign-in before the verification step.",
      account_verification_required: "The participant account requires both email and phone verification.",
      challenge_required: "Request a new code before trying to verify it.",
      invalid_code: "The code could not be verified. Use the latest test message and try again.",
      challenge_expired: "The code expired. Request a new code and try again.",
      retry_limited: "Too many attempts. Wait briefly, then request a new code and try again.",
      recovery_unconfigured: "Recovery is closed. Named custodians, verified email recovery details and the reset rehearsal remain pending.",
      factor_already_enrolled: "The Super Admin phone is already verified. Request a new SMS code instead.",
      unavailable: "The session check is unavailable. Your entered code remains here so you can retry.",
    },
  },
  ar: {
    eyebrow: "MSRC ٢٠٢٧ / معاينة أمنية محلية",
    title: "التحقق من الوصول خطوة بخطوة.",
    intro: "يتحقق المشاركون من البريد والهاتف دون مصادقة ثنائية. يدخل أعضاء الفريق العاديون بكلمة المرور ثم رمز بريد جديد. يحتفظ المشرفون الأعلى بعامل SMS الثاني. جرّب المسارات بهويات مصطنعة؛ يظل الوصول الفعلي مغلقًا.",
    synthetic: "هويات مصطنعة · للاختبار المحلي فقط",
    simulation: "تسجيل الدخول بكلمة المرور مُحاكى. لا تُجمع كلمة مرور أو أرقام هاتف فعلية، ولا تُرسل رسائل SMS أو رسائل بريد فعلية.",
    start: "محاكاة دخول الفريق بكلمة المرور",
    startSuperAdmin: "محاكاة دخول المشرف الأعلى بكلمة المرور",
    participant: "محاكاة دخول المشارك بكلمة المرور",
    restart: "بدء جلسة مصطنعة جديدة",
    pending: "جارٍ التنفيذ…",
    sessionTitle: "الجلسة والتحقق",
    active: "الجلسة نشطة",
    revoked: "أُلغيت الجلسة",
    expired: "انتهت الجلسة",
    noSession: "لا توجد جلسة مصطنعة",
    staff: "عضو فريق مصطنع",
    superAdminLabel: "مشرف أعلى مصطنع",
    participantLabel: "مشارك مصطنع",
    passwordLabel: "تسجيل الدخول بكلمة المرور",
    passwordVerified: "مُحاكى ومكتمل",
    verificationTitle: "التحقق من الحساب",
    emailLabel: "التحقق من البريد الإلكتروني",
    phoneLabel: "التحقق من الهاتف",
    verificationComplete: "تم التحقق من البريد والهاتف",
    verificationPending: "يلزم التحقق من البريد والهاتف",
    emailPending: "يلزم التحقق من البريد",
    phonePending: "يلزم التحقق من الهاتف",
    verifiedStatus: "تم التحقق",
    missing: "لم يُتحقق منه",
    assuranceLabel: "عامل المصادقة الثاني للمشرف الأعلى",
    staffEmailLabel: "تحقق البريد الإضافي للفريق",
    staffEmailAssured: "اجتاز تحقق البريد لهذه الجلسة",
    participantAssuranceLabel: "المصادقة الثنائية للمشارك",
    assured: "تم التحقق من عامل SMS الثاني",
    participantAssurance: "المصادقة الثنائية غير مطلوبة للمشاركين",
    accessClosed: "يظل الوصول الفعلي بصلاحيات مميزة ومسارات العمل التشغيلية مغلقًا.",
    absolute: "انتهاء المدة القصوى",
    idle: "انتهاء مهلة الخمول",
    setupTitle: "التحقق عبر SMS للمشرف الأعلى",
    setupIntro: "بعد محاكاة الدخول بكلمة المرور، أكّد الهاتف المصطنع برمز SMS. تعرض المعاينة رسالة اختبار أدناه ولا تُرسل رسالة فعلية.",
    enroll: "إنشاء تحقق SMS مصطنع للمشرف الأعلى",
    challengeTitle: "إدخال رمز SMS",
    challengeIntro: "استخدم أحدث رمز مكوّن من ستة أرقام في صندوق اختبار SMS المصطنع. يؤدي طلب رمز بديل إلى إبطال الرمز السابق.",
    challenge: "طلب رمز SMS مصطنع جديد",
    codeLabel: "رمز SMS المكوّن من ستة أرقام",
    codeHint: "الصق أحدث رمز اختبار أو اكتبه. تُقبل الأرقام العربية واللاتينية. لا تُحفظ الرموز في تخزين المتصفح.",
    verify: "التحقق من رمز SMS",
    codeValidation: "أدخل رمز تحقق مكوّنًا من ستة أرقام.",
    confirmed: "اجتازت جلسة المشرف الأعلى المصطنعة تحقق كلمة المرور وSMS. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
    staffEmailTitle: "إكمال تحقق البريد للفريق",
    staffEmailIntro: "بعد الدخول بكلمة المرور، اطلب رمزًا جديدًا إلى بريد الحساب الموثّق. تظهر الرسالة في صندوق الاختبار في هذه المعاينة المحلية؛ ولا يُرسل بريد فعلي.",
    staffEmailScope: "تنتهي صلاحية الرمز بعد خمس دقائق. يخص هذا التحقق الإضافي جلسة الدخول الحالية ولا يُعدّ مصادقة Supabase متعددة العوامل أو AAL2. يتطلب الدخول الجديد تحققًا جديدًا؛ ولا يتطلبه تحديث رمز الجلسة.",
    staffEmailCodeLabel: "رمز بريد الفريق المكوّن من ستة أرقام",
    staffEmailConfirmed: "اجتازت جلسة الفريق المصطنعة تحقق كلمة المرور والبريد الإضافي. يظل وصول الفريق الفعلي مغلقًا.",
    staffEmailExpired: "انتهت صلاحية رمز البريد هذا. اطلب رمزًا جديدًا للمتابعة.",
    staffEmailDeliveryFailed: "تعذر طلب رمز البريد. انتظر ثم حاول مجددًا. يبقى الرمز المدخل هنا؛ ويظل وصول الفريق مغلقًا.",
    staffEmailRetryLimited: "تجاوزت حدّ المحاولات أو الطلبات. بعد خمسة رموز غير صحيحة يُعلّق تحقق البريد لمدة ١٥ دقيقة. قد تتطلب حدود الإرسال انتظارًا أطول. انتظر ثم اطلب رمزًا جديدًا.",
    emailResendWait: "يمكنك طلب رمز بريد آخر بعد",
    participantNote: "يواصل المشاركون تسجيل الدخول بالبريد الإلكتروني وكلمة المرور. يلزم التحقق من البريد والهاتف للحساب؛ ولا يمنح ذلك مصادقة ثنائية أو وصول الفريق.",
    participantChecksPassed: "اجتاز حساب المشارك المصطنع كلا التحققين المطلوبين. تظل جلسته AAL1 دون إعداد عامل مصادقة ثنائية.",
    emailTitle: "التحقق من بريد المشارك",
    emailIntro: "أنشئ رسالة بريد مصطنعة ثم أدخل رمزها. لا تُرسل رسالة بريد فعلية.",
    emailChallenge: "طلب رمز بريد مصطنع",
    emailCodeLabel: "رمز التحقق من البريد المكوّن من ستة أرقام",
    emailVerify: "التحقق من رمز البريد",
    phoneTitle: "التحقق من هاتف المشارك",
    phoneIntro: "أنشئ رسالة SMS مصطنعة ثم أدخل رمزها. لا يمنح التحقق من الهاتف مصادقة ثنائية للمشارك أو وصول الفريق.",
    phoneCodeLabel: "رمز التحقق من الهاتف المكوّن من ستة أرقام",
    phoneVerify: "التحقق من هاتف المشارك",
    inboxTitle: "صندوق الرسائل المصطنعة للاختبار",
    inboxNote: "رسائل اختبار محلية فقط. لا تُرسل إلى هاتف أو عنوان بريد. تختفي الرموز بعد التحقق أو تسجيل الخروج أو إعادة تحميل المتصفح.",
    smsMessage: "رسالة SMS مصطنعة",
    emailMessage: "رسالة بريد مصطنعة",
    smsDestination: "هاتف مصطنع",
    emailDestination: "بريد مصطنع",
    messageCode: "رمز التحقق التجريبي",
    messageExpiry: "انتهاء صلاحية الرمز",
    messageDelivery: "تسليم تجريبي فقط",
    checkAccess: "التحقق من وصول الفريق المصطنع",
    checkParticipant: "التحقق من حساب المشارك المصطنع",
    refresh: "تحديث رمز الجلسة المصطنعة",
    reauthenticate: "محاكاة إعادة المصادقة بكلمة المرور",
    logout: "تسجيل الخروج من الجلسة المصطنعة",
    retry: "إعادة محاولة التحقق من الجلسة",
    recoveryTitle: "فقدت الوصول إلى بريدك أو هاتفك؟",
    recoveryIntro: "تظل الاستعادة مغلقة. يلزم التحقق الحضوري من الهوية ودوران منفصلان للموافقة وإعادة الضبط لدى المشرفين الأعلى؛ ولا تزال أسماء المسؤولين وتفاصيل استعادة البريد معلّقة. لا تتجاوز استعادة كلمة المرور تحقق بريد الفريق أو العامل الثاني للمشرف الأعلى.",
    recovery: "التحقق من إتاحة الاستعادة",
    policyTitle: "سياسة الجلسات المحددة",
    participantPolicy: "المشاركون: ٧٢ ساعة كحد أقصى من تسجيل الدخول الأصلي.",
    privilegedPolicy: "الفريق: مهلة خمول ٣٠ دقيقة ومدة قصوى ٨ ساعات من تسجيل الدخول الأصلي.",
    refreshPolicy: "تحديث رمز الجلسة لا يبدأ مدة قصوى جديدة. يُفرض انتهاء الجلسة على الخادم.",
    unsetPolicy: "لم تُحدد مدة صلاحية المصادقة الحديثة أو توقيت التحذير قبل انتهاء الجلسة. تظل الإجراءات الحساسة مغلقة.",
    emailPolicy: "تسليم البريد في الإنتاج غير مُعدّ. تبقى رسائل البريد باللغة الإنجليزية فقط. لا تزال موافقات SMS والخصوصية والاحتفاظ بالبيانات ومواقعها معلّقة. تستخدم هذه المعاينة رسائل اختبار فقط.",
    scenarioTitle: "اختبارات إلغاء مصطنعة",
    scenarioNote: "تلغي هذه الاختبارات الجلسة المصطنعة الحالية فقط. لا تغيّر حسابًا مُدارًا أو صلاحية أو هاتفًا أو عامل مصادقة فعليًا.",
    suspend: "محاكاة التعليق",
    factorReset: "محاكاة الإلغاء بعد إعادة ضبط العامل",
    emailChange: "محاكاة تغيير البريد الموثّق",
    roleRevocation: "محاكاة إلغاء دور الفريق",
    participantAllowed: "اجتاز اختبار التحقق من المشارك المصطنع. يظل الوصول التشغيلي الفعلي مغلقًا.",
    emailVerifiedPhonePending: "تم التحقق من بريد المشارك المصطنع. لا يزال التحقق من الهاتف مطلوبًا.",
    participantReauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. تبقى حالة التحقق للمشارك محفوظة؛ ولا تُطلب مصادقة ثنائية.",
    staffReauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. على أعضاء الفريق العاديين إكمال تحقق بريد جديد.",
    messages: {
      started: "اكتملت محاكاة الدخول بكلمة المرور. تابع التحقق المطلوب لهذه الهوية.",
      enrolled: "طلب تحقق SMS مصطنع للمشرف الأعلى جاهز في صندوق الاختبار. لم تُرسل رسالة فعلية.",
      challenge_created: "رمز SMS مصطنع جديد جاهز. أُبطل الرمز السابق.",
      email_challenge_created: "رمز بريد مصطنع جاهز في صندوق الاختبار. لم تُرسل رسالة بريد فعلية.",
      verified: "تم التحقق من عامل SMS الثاني لهذه الجلسة المصطنعة للمشرف الأعلى.",
      staff_email_verified: "اجتاز تحقق البريد الإضافي لهذه الجلسة المصطنعة للفريق. يظل وصول الفريق الفعلي مغلقًا.",
      phone_verified: "تم التحقق من هاتف المشارك المصطنع. تظل المصادقة الثنائية غير مطلوبة للمشارك.",
      email_verified: "تم التحقق من بريد المشارك المصطنع. اكتمل كلا التحققين المطلوبين للحساب.",
      protected_allowed: "اجتاز اختبار وصول الفريق المصطنع. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
      refreshed: "تم تحديث رمز الجلسة المصطنعة. لم يتغير وقت انتهاء المدة القصوى الأصلي.",
      logged_out: "تم تسجيل الخروج من الجلسة المصطنعة. لم تعد جلستها السابقة تجتاز التحقق من الوصول.",
      suspended: "أُلغيت الجلسة المصطنعة بواسطة اختبار التعليق.",
      factor_reset_revoked: "أُلغي التحقق والجلسات المصطنعة. تظل استعادة عامل المصادقة الفعلي مغلقة.",
      reauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. على المشرفين الأعلى التحقق من رمز SMS جديد.",
      no_session: "ابدأ جلسة مصطنعة للمتابعة.",
      session_revoked: "أُلغيت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      session_expired: "انتهت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      mfa_required: "يتطلب وصول المشرف الأعلى الدخول بكلمة المرور والتحقق من عامل SMS الثاني.",
      staff_email_check_required: "يتطلب وصول الفريق الدخول بكلمة المرور وتحقق بريد جديدًا لهذه الجلسة.",
      password_auth_required: "أكمل تسجيل الدخول بكلمة المرور قبل خطوة التحقق.",
      account_verification_required: "يتطلب حساب المشارك التحقق من البريد والهاتف معًا.",
      challenge_required: "اطلب رمزًا جديدًا قبل محاولة التحقق منه.",
      invalid_code: "تعذر التحقق من الرمز. استخدم أحدث رسالة اختبار وحاول مجددًا.",
      challenge_expired: "انتهت صلاحية الرمز. اطلب رمزًا جديدًا وحاول مجددًا.",
      retry_limited: "تجاوزت عدد المحاولات. انتظر قليلًا ثم اطلب رمزًا جديدًا وحاول مجددًا.",
      recovery_unconfigured: "الاستعادة مغلقة. لا تزال أسماء المسؤولين وتفاصيل استعادة البريد الموثّقة وتجربة إعادة الضبط معلّقة.",
      factor_already_enrolled: "تم التحقق من هاتف المشرف الأعلى بالفعل. اطلب رمز SMS جديدًا بدلًا من الإعداد.",
      unavailable: "التحقق من الجلسة غير متاح. يبقى الرمز المدخل هنا لتتمكن من إعادة المحاولة.",
    },
  },
} satisfies Record<Locale, unknown>;

export type StaffSecurityMessage = keyof typeof staffSecurityCopy.en.messages;
