import type { Locale } from "@/lib/i18n";

// LOC-01 / AUTH-02/04/05: regular staff have an additional session email check;
// Super Admin authenticator MFA and participant email verification stay distinct.
export const staffSecurityCopy = {
  en: {
    eyebrow: "MSRC 2027 / local security preview",
    title: "Verify access, step by step.",
    intro: "Participants verify email without MFA. Regular staff use password sign-in followed by a fresh email code. Super Admins use an authenticator app as their second factor. Try the flows with synthetic identities; live access remains closed.",
    synthetic: "Synthetic identities · local test only",
    simulation: "Password sign-in is simulated. No real password is collected and no managed account or factor is created. Live access remains closed.",
    isolatedSimulation: "Password sign-in is simulated. No real password is collected and no managed account or factor is created. Staff test codes are sent only to the approved isolated test inbox.",
    isolatedEmailIntro: "Request a fresh test code, then check the approved isolated email inbox. The code is sent by email and is never shown in this preview. Participant and Super Admin test flows remain unchanged.",
    isolatedEmailChallenge: "Send an isolated test email code",
    isolatedEmailSent: "The test email was accepted for delivery. Check Inbox and Spam in the approved test mailbox, then enter the newest six-digit code. Delivery may take a moment.",
    start: "Simulate staff password sign-in",
    startSuperAdmin: "Simulate Super Admin password sign-in",
    participant: "Simulate participant password sign-in",
    restart: "Start a new synthetic session",
    pending: "Working…",
    sessionTitle: "Session and verification",
    active: "Session active",
    revoked: "Session revoked",
    expired: "Session expired",
    noSession: "No synthetic session",
    staff: "Synthetic staff",
    superAdminLabel: "Synthetic Super Admin",
    participantLabel: "Synthetic participant",
    passwordLabel: "Password sign-in",
    passwordVerified: "Simulated and complete",
    verificationTitle: "Account verification",
    emailLabel: "Email verification",
    verificationComplete: "Email verified",
    verificationPending: "Email verification required",
    verifiedStatus: "Verified",
    missing: "Not verified",
    assuranceLabel: "Super Admin second factor",
    staffEmailLabel: "Additional staff email check",
    staffEmailAssured: "Email check passed for this session",
    participantAssuranceLabel: "Participant MFA",
    assured: "Authenticator second factor verified",
    participantAssurance: "MFA not required for participants",
    accessClosed: "Live privileged access and operational workflows remain closed.",
    absolute: "Absolute expiry",
    idle: "Idle expiry",
    setupTitle: "Set up a Super Admin authenticator",
    setupIntro: "Use an authenticator app for this local synthetic identity. Create a setup, then scan its QR code or enter the manual key in your app. This does not enroll a managed account.",
    enroll: "Create synthetic authenticator setup",
    qrTitle: "Add the synthetic account to your authenticator app",
    qrIntro: "Scan this QR code in your authenticator app. If scanning is unavailable, use the manual setup below. Keep the setup key private.",
    qrAlt: "QR code for the synthetic MSRC authenticator account. The same setup is available as a manual key below.",
    manualSetup: "Use a manual setup key instead",
    secretLabel: "Synthetic setup key",
    manualInstructions: "In your app, choose a time-based account and enter this key. Label it MSRC synthetic preview. Use six digits, a 30-second period and SHA-1 if the app asks. These are local protocol settings, not approved production operating controls.",
    setupLost: "Setup details disappear on browser reload. Start a new synthetic setup if you have not saved it in your authenticator app.",
    restartSetup: "Start a new synthetic Super Admin setup",
    challengeTitle: "Enter the authenticator code",
    challengeIntro: "Enter the current six-digit code from your authenticator app. A used code cannot be accepted again. If it changes, use the next code; check your device clock if verification keeps failing.",
    challenge: "Start a new authenticator check",
    codeLabel: "Six-digit authenticator code",
    codeHint: "Paste or type the latest test code. Arabic and Latin digits are accepted. Codes are never saved in browser storage.",
    verify: "Verify authenticator code",
    codeValidation: "Enter a six-digit verification code.",
    confirmed: "Password and authenticator checks passed for this synthetic Super Admin session. Live privileged access remains closed.",
    staffEmailTitle: "Complete the staff email check",
    staffEmailIntro: "After password sign-in, request a fresh code at the account’s verified email address. In this local preview the message appears in the test inbox; no email is sent.",
    staffEmailScope: "The code expires after five minutes. This additional check belongs to this login session and is not Supabase MFA or AAL2. A new login requires a fresh check; refreshing a token does not.",
    staffEmailCodeLabel: "Six-digit staff email code",
    staffEmailConfirmed: "Password and the additional email check passed for this synthetic staff session. Live staff access remains closed.",
    staffEmailExpired: "This email code has expired. Request a new code to continue.",
    staffEmailDeliveryFailed: "The email code could not be requested. Wait, then try again. Your entered code remains here; staff access is still closed.",
    staffEmailRetryLimited: "Too many incorrect codes or requests. Five incorrect entries pause the email check for 15 minutes. Send limits may require a longer wait. Wait, then request a new code.",
    emailResendWait: "You can request another email code after",
    participantNote: "Participants use email and password to sign in and verify the account’s email. MFA is not required, and email verification does not grant staff access.",
    participantChecksPassed: "The synthetic participant account has verified its email. Its session remains AAL1 and no MFA factor is enrolled.",
    emailTitle: "Verify the participant email",
    emailIntro: "Create a synthetic email message, then enter its code. No real email is sent.",
    emailChallenge: "Request a synthetic email code",
    emailCodeLabel: "Six-digit email verification code",
    emailVerify: "Verify email code",
    inboxTitle: "Synthetic test inbox",
    inboxNote: "Local test messages only. Nothing is sent to an email address. Codes disappear after verification, sign-out or browser reload.",
    emailMessage: "Synthetic email message",
    emailDestination: "Synthetic email",
    messageCode: "Test verification code",
    messageExpiry: "Code expiry",
    messageDelivery: "Test-only delivery",
    checkAccess: "Check synthetic staff access",
    checkParticipant: "Check synthetic participant verification",
    refresh: "Refresh synthetic token",
    reauthenticate: "Simulate password reauthentication",
    logout: "Log out synthetic session",
    retry: "Retry session check",
    recoveryTitle: "Lost access to your email or authenticator?",
    recoveryIntro: "Recovery remains closed. In-person identity review and distinct Super Admin approval and reset roles are required; named custodians and email recovery details remain pending. Password recovery cannot bypass the required staff email check or Super Admin second factor.",
    recovery: "Check recovery availability",
    policyTitle: "Configured session policy",
    participantPolicy: "Participants: 72 hours maximum from the original sign-in.",
    privilegedPolicy: "Staff: 30 minutes idle and 8 hours maximum from the original sign-in.",
    refreshPolicy: "Refreshing a token does not restart either absolute lifetime. Session expiry is enforced on the server.",
    unsetPolicy: "Recent-authentication age and timeout-warning lead remain unset. Sensitive actions stay closed.",
    emailPolicy: "Production email delivery is unconfigured. Email messages stay English-only. Authenticator recovery, privacy, retention and data-location approvals remain pending. This preview uses test messages only.",
    scenarioTitle: "Synthetic revocation checks",
    scenarioNote: "These checks revoke only the current synthetic session. They do not change a managed account, grant or live factor.",
    suspend: "Simulate suspension",
    factorReset: "Simulate factor-reset revocation",
    emailChange: "Simulate verified-email change",
    roleRevocation: "Simulate staff-role revocation",
    participantAllowed: "The synthetic participant verification check passed. Live operational access remains closed.",
    participantReauthenticated: "A new simulated password session started. Participant verification status is retained; MFA is not required.",
    staffReauthenticated: "A new simulated password session started. Regular staff must complete a fresh email check.",
    messages: {
      started: "Synthetic password sign-in completed. Continue with the verification checks for this identity.",
      enrolled: "Synthetic authenticator setup created. Scan the QR code or use the manual key, then enter the current code from your app.",
      challenge_created: "A new authenticator check is ready. Enter the current unused code from your app.",
      email_challenge_created: "A synthetic email code is ready in the test inbox. No real email was sent.",
      verified: "Authenticator second factor verified for this synthetic Super Admin session.",
      staff_email_verified: "The additional email check passed for this synthetic staff session. Live staff access remains closed.",
      email_verified: "Synthetic participant email verified. Account verification is complete.",
      protected_allowed: "The synthetic staff check passed. Live privileged access remains closed.",
      refreshed: "Synthetic token refreshed. The original absolute expiry is unchanged.",
      logged_out: "Synthetic session logged out. Its previous session can no longer pass access checks.",
      suspended: "Synthetic session revoked by the suspension check.",
      factor_reset_revoked: "Synthetic assurance and sessions revoked. Live factor recovery remains closed.",
      reauthenticated: "A new simulated password session started. Super Admins must complete a fresh authenticator check.",
      no_session: "Start a synthetic session to continue.",
      session_revoked: "This session was revoked. Start a new synthetic session to continue.",
      session_expired: "This session has expired. Start a new synthetic session to continue.",
      mfa_required: "Super Admin access requires password sign-in and a verified authenticator second factor.",
      staff_email_check_required: "Staff access requires password sign-in and a fresh email check for this session.",
      password_auth_required: "Complete password sign-in before the verification step.",
      account_verification_required: "The participant account requires verified email.",
      challenge_required: "Request a new code before trying to verify it.",
      invalid_code: "The code could not be verified. Use the current code and try again.",
      challenge_expired: "The code expired. Request a new code and try again.",
      retry_limited: "Too many attempts. Wait briefly, then request a new code and try again.",
      recovery_unconfigured: "Recovery is closed. Named custodians, verified email recovery details and the reset rehearsal remain pending.",
      factor_already_enrolled: "This synthetic authenticator is already set up. Start a new authenticator check instead.",
      unavailable: "The session check is unavailable. Your entered code remains here so you can retry.",
    },
  },
  ar: {
    eyebrow: "MSRC ٢٠٢٧ / معاينة أمنية محلية",
    title: "التحقق من الوصول خطوة بخطوة.",
    intro: "يتحقق المشاركون من البريد دون مصادقة ثنائية. يدخل أعضاء الفريق العاديون بكلمة المرور ثم رمز بريد جديد. يستخدم المشرفون الأعلى تطبيق مصادقة كعامل ثانٍ. جرّب المسارات بهويات مصطنعة؛ يظل الوصول الفعلي مغلقًا.",
    synthetic: "هويات مصطنعة · للاختبار المحلي فقط",
    simulation: "تسجيل الدخول بكلمة المرور مُحاكى. لا تُجمع كلمة مرور فعلية ولا يُنشأ حساب أو عامل مُدار. يظل الوصول الفعلي مغلقًا.",
    isolatedSimulation: "تسجيل الدخول بكلمة المرور مُحاكى. لا تُجمع كلمة مرور فعلية ولا يُنشأ حساب أو عامل مُدار. تُرسل رموز اختبار الفريق إلى صندوق الاختبار المعزول المعتمد فقط.",
    isolatedEmailIntro: "اطلب رمز اختبار جديدًا ثم تحقق من صندوق البريد المعزول المعتمد. يُرسل الرمز بالبريد ولا يظهر في هذه المعاينة. تبقى مسارات اختبار المشارك والمشرف الأعلى كما هي.",
    isolatedEmailChallenge: "إرسال رمز بريد للاختبار المعزول",
    isolatedEmailSent: "قُبل بريد الاختبار للتسليم. تحقق من الوارد والبريد غير المرغوب فيه في صندوق الاختبار المعتمد ثم أدخل أحدث رمز مكوّن من ستة أرقام. قد يستغرق التسليم قليلًا من الوقت.",
    start: "محاكاة دخول الفريق بكلمة المرور",
    startSuperAdmin: "محاكاة دخول المشرف الأعلى بكلمة المرور",
    participant: "محاكاة دخول المشارك بكلمة المرور",
    restart: "بدء جلسة مصطنعة جديدة",
    pending: "جارٍ التنفيذ…",
    sessionTitle: "الجلسة والتحقق",
    active: "الجلسة نشطة",
    revoked: "أُلغيت الجلسة",
    expired: "انتهت الجلسة",
    noSession: "لا توجد جلسة مصطنعة",
    staff: "عضو فريق مصطنع",
    superAdminLabel: "مشرف أعلى مصطنع",
    participantLabel: "مشارك مصطنع",
    passwordLabel: "تسجيل الدخول بكلمة المرور",
    passwordVerified: "مُحاكى ومكتمل",
    verificationTitle: "التحقق من الحساب",
    emailLabel: "التحقق من البريد الإلكتروني",
    verificationComplete: "تم التحقق من البريد",
    verificationPending: "يلزم التحقق من البريد",
    verifiedStatus: "تم التحقق",
    missing: "لم يُتحقق منه",
    assuranceLabel: "عامل المصادقة الثاني للمشرف الأعلى",
    staffEmailLabel: "تحقق البريد الإضافي للفريق",
    staffEmailAssured: "اجتاز تحقق البريد لهذه الجلسة",
    participantAssuranceLabel: "المصادقة الثنائية للمشارك",
    assured: "تم التحقق من عامل تطبيق المصادقة الثاني",
    participantAssurance: "المصادقة الثنائية غير مطلوبة للمشاركين",
    accessClosed: "يظل الوصول الفعلي بصلاحيات مميزة ومسارات العمل التشغيلية مغلقًا.",
    absolute: "انتهاء المدة القصوى",
    idle: "انتهاء مهلة الخمول",
    setupTitle: "إعداد تطبيق المصادقة للمشرف الأعلى",
    setupIntro: "استخدم تطبيق مصادقة لهذه الهوية المصطنعة المحلية. أنشئ الإعداد ثم امسح رمز QR أو أدخل المفتاح يدويًا في التطبيق. لا يضيف ذلك عاملًا إلى حساب مُدار.",
    enroll: "إنشاء إعداد مصادقة مصطنع",
    qrTitle: "إضافة الحساب المصطنع إلى تطبيق المصادقة",
    qrIntro: "امسح رمز QR هذا في تطبيق المصادقة. إذا تعذّر المسح، استخدم الإعداد اليدوي أدناه. حافظ على سرية مفتاح الإعداد.",
    qrAlt: "رمز QR لحساب المصادقة المصطنع لـMSRC. يتوفر الإعداد نفسه كمفتاح يدوي أدناه.",
    manualSetup: "استخدام مفتاح إعداد يدوي بدلًا من المسح",
    secretLabel: "مفتاح الإعداد المصطنع",
    manualInstructions: "اختر حسابًا يعتمد على الوقت في التطبيق وأدخل هذا المفتاح. سمّه MSRC synthetic preview. إذا طُلب منك، اختر ستة أرقام وفترة ٣٠ ثانية وSHA-1. هذه إعدادات بروتوكول محلية وليست ضوابط تشغيل معتمدة للإنتاج.",
    setupLost: "تختفي تفاصيل الإعداد عند إعادة تحميل المتصفح. ابدأ إعدادًا مصطنعًا جديدًا إذا لم تحفظه في تطبيق المصادقة.",
    restartSetup: "بدء إعداد مصطنع جديد للمشرف الأعلى",
    challengeTitle: "إدخال رمز تطبيق المصادقة",
    challengeIntro: "أدخل الرمز الحالي المكوّن من ستة أرقام من تطبيق المصادقة. لا يُقبل الرمز المُستخدم مرة أخرى. إذا تغيّر الرمز، استخدم الرمز التالي؛ وتحقق من ساعة الجهاز إذا استمر فشل التحقق.",
    challenge: "بدء تحقق جديد بتطبيق المصادقة",
    codeLabel: "رمز تطبيق المصادقة المكوّن من ستة أرقام",
    codeHint: "الصق أحدث رمز اختبار أو اكتبه. تُقبل الأرقام العربية واللاتينية. لا تُحفظ الرموز في تخزين المتصفح.",
    verify: "التحقق من رمز تطبيق المصادقة",
    codeValidation: "أدخل رمز تحقق مكوّنًا من ستة أرقام.",
    confirmed: "اجتازت جلسة المشرف الأعلى المصطنعة تحقق كلمة المرور وتطبيق المصادقة. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
    staffEmailTitle: "إكمال تحقق البريد للفريق",
    staffEmailIntro: "بعد الدخول بكلمة المرور، اطلب رمزًا جديدًا إلى بريد الحساب الموثّق. تظهر الرسالة في صندوق الاختبار في هذه المعاينة المحلية؛ ولا يُرسل بريد فعلي.",
    staffEmailScope: "تنتهي صلاحية الرمز بعد خمس دقائق. يخص هذا التحقق الإضافي جلسة الدخول الحالية ولا يُعدّ مصادقة Supabase متعددة العوامل أو AAL2. يتطلب الدخول الجديد تحققًا جديدًا؛ ولا يتطلبه تحديث رمز الجلسة.",
    staffEmailCodeLabel: "رمز بريد الفريق المكوّن من ستة أرقام",
    staffEmailConfirmed: "اجتازت جلسة الفريق المصطنعة تحقق كلمة المرور والبريد الإضافي. يظل وصول الفريق الفعلي مغلقًا.",
    staffEmailExpired: "انتهت صلاحية رمز البريد هذا. اطلب رمزًا جديدًا للمتابعة.",
    staffEmailDeliveryFailed: "تعذر طلب رمز البريد. انتظر ثم حاول مجددًا. يبقى الرمز المدخل هنا؛ ويظل وصول الفريق مغلقًا.",
    staffEmailRetryLimited: "تجاوزت حدّ المحاولات أو الطلبات. بعد خمسة رموز غير صحيحة يُعلّق تحقق البريد لمدة ١٥ دقيقة. قد تتطلب حدود الإرسال انتظارًا أطول. انتظر ثم اطلب رمزًا جديدًا.",
    emailResendWait: "يمكنك طلب رمز بريد آخر بعد",
    participantNote: "يدخل المشاركون بالبريد الإلكتروني وكلمة المرور ويتحققون من بريد الحساب. لا تتطلب حساباتهم مصادقة ثنائية، ولا يمنح التحقق من البريد وصول الفريق.",
    participantChecksPassed: "تحقق حساب المشارك المصطنع من بريده الإلكتروني. تظل جلسته AAL1 دون إعداد عامل مصادقة ثنائية.",
    emailTitle: "التحقق من بريد المشارك",
    emailIntro: "أنشئ رسالة بريد مصطنعة ثم أدخل رمزها. لا تُرسل رسالة بريد فعلية.",
    emailChallenge: "طلب رمز بريد مصطنع",
    emailCodeLabel: "رمز التحقق من البريد المكوّن من ستة أرقام",
    emailVerify: "التحقق من رمز البريد",
    inboxTitle: "صندوق الرسائل المصطنعة للاختبار",
    inboxNote: "رسائل اختبار محلية فقط. لا تُرسل إلى عنوان بريد. تختفي الرموز بعد التحقق أو تسجيل الخروج أو إعادة تحميل المتصفح.",
    emailMessage: "رسالة بريد مصطنعة",
    emailDestination: "بريد مصطنع",
    messageCode: "رمز التحقق التجريبي",
    messageExpiry: "انتهاء صلاحية الرمز",
    messageDelivery: "تسليم تجريبي فقط",
    checkAccess: "التحقق من وصول الفريق المصطنع",
    checkParticipant: "التحقق من حساب المشارك المصطنع",
    refresh: "تحديث رمز الجلسة المصطنعة",
    reauthenticate: "محاكاة إعادة المصادقة بكلمة المرور",
    logout: "تسجيل الخروج من الجلسة المصطنعة",
    retry: "إعادة محاولة التحقق من الجلسة",
    recoveryTitle: "فقدت الوصول إلى بريدك أو تطبيق المصادقة؟",
    recoveryIntro: "تظل الاستعادة مغلقة. يلزم التحقق الحضوري من الهوية ودوران منفصلان للموافقة وإعادة الضبط لدى المشرفين الأعلى؛ ولا تزال أسماء المسؤولين وتفاصيل استعادة البريد معلّقة. لا تتجاوز استعادة كلمة المرور تحقق بريد الفريق أو العامل الثاني للمشرف الأعلى.",
    recovery: "التحقق من إتاحة الاستعادة",
    policyTitle: "سياسة الجلسات المحددة",
    participantPolicy: "المشاركون: ٧٢ ساعة كحد أقصى من تسجيل الدخول الأصلي.",
    privilegedPolicy: "الفريق: مهلة خمول ٣٠ دقيقة ومدة قصوى ٨ ساعات من تسجيل الدخول الأصلي.",
    refreshPolicy: "تحديث رمز الجلسة لا يبدأ مدة قصوى جديدة. يُفرض انتهاء الجلسة على الخادم.",
    unsetPolicy: "لم تُحدد مدة صلاحية المصادقة الحديثة أو توقيت التحذير قبل انتهاء الجلسة. تظل الإجراءات الحساسة مغلقة.",
    emailPolicy: "تسليم البريد في الإنتاج غير مُعدّ. تبقى رسائل البريد باللغة الإنجليزية فقط. لا تزال موافقات استعادة تطبيق المصادقة والخصوصية والاحتفاظ بالبيانات ومواقعها معلّقة. تستخدم هذه المعاينة رسائل اختبار فقط.",
    scenarioTitle: "اختبارات إلغاء مصطنعة",
    scenarioNote: "تلغي هذه الاختبارات الجلسة المصطنعة الحالية فقط. لا تغيّر حسابًا مُدارًا أو صلاحية أو عامل مصادقة فعليًا.",
    suspend: "محاكاة التعليق",
    factorReset: "محاكاة الإلغاء بعد إعادة ضبط العامل",
    emailChange: "محاكاة تغيير البريد الموثّق",
    roleRevocation: "محاكاة إلغاء دور الفريق",
    participantAllowed: "اجتاز اختبار التحقق من المشارك المصطنع. يظل الوصول التشغيلي الفعلي مغلقًا.",
    participantReauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. تبقى حالة التحقق للمشارك محفوظة؛ ولا تُطلب مصادقة ثنائية.",
    staffReauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. على أعضاء الفريق العاديين إكمال تحقق بريد جديد.",
    messages: {
      started: "اكتملت محاكاة الدخول بكلمة المرور. تابع التحقق المطلوب لهذه الهوية.",
      enrolled: "أُنشئ إعداد تطبيق المصادقة المصطنع. امسح رمز QR أو استخدم المفتاح اليدوي ثم أدخل الرمز الحالي من التطبيق.",
      challenge_created: "تحقق جديد بتطبيق المصادقة جاهز. أدخل الرمز الحالي غير المُستخدم من التطبيق.",
      email_challenge_created: "رمز بريد مصطنع جاهز في صندوق الاختبار. لم تُرسل رسالة بريد فعلية.",
      verified: "تم التحقق من عامل تطبيق المصادقة الثاني لهذه الجلسة المصطنعة للمشرف الأعلى.",
      staff_email_verified: "اجتاز تحقق البريد الإضافي لهذه الجلسة المصطنعة للفريق. يظل وصول الفريق الفعلي مغلقًا.",
      email_verified: "تم التحقق من بريد المشارك المصطنع. اكتمل التحقق من الحساب.",
      protected_allowed: "اجتاز اختبار وصول الفريق المصطنع. يظل الوصول الفعلي بصلاحيات مميزة مغلقًا.",
      refreshed: "تم تحديث رمز الجلسة المصطنعة. لم يتغير وقت انتهاء المدة القصوى الأصلي.",
      logged_out: "تم تسجيل الخروج من الجلسة المصطنعة. لم تعد جلستها السابقة تجتاز التحقق من الوصول.",
      suspended: "أُلغيت الجلسة المصطنعة بواسطة اختبار التعليق.",
      factor_reset_revoked: "أُلغي التحقق والجلسات المصطنعة. تظل استعادة عامل المصادقة الفعلي مغلقة.",
      reauthenticated: "بدأت جلسة جديدة بمحاكاة كلمة المرور. على المشرفين الأعلى إكمال تحقق جديد بتطبيق المصادقة.",
      no_session: "ابدأ جلسة مصطنعة للمتابعة.",
      session_revoked: "أُلغيت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      session_expired: "انتهت هذه الجلسة. ابدأ جلسة مصطنعة جديدة للمتابعة.",
      mfa_required: "يتطلب وصول المشرف الأعلى الدخول بكلمة المرور والتحقق من عامل تطبيق المصادقة الثاني.",
      staff_email_check_required: "يتطلب وصول الفريق الدخول بكلمة المرور وتحقق بريد جديدًا لهذه الجلسة.",
      password_auth_required: "أكمل تسجيل الدخول بكلمة المرور قبل خطوة التحقق.",
      account_verification_required: "يتطلب حساب المشارك بريدًا موثّقًا.",
      challenge_required: "اطلب رمزًا جديدًا قبل محاولة التحقق منه.",
      invalid_code: "تعذر التحقق من الرمز. استخدم الرمز الحالي وحاول مجددًا.",
      challenge_expired: "انتهت صلاحية الرمز. اطلب رمزًا جديدًا وحاول مجددًا.",
      retry_limited: "تجاوزت عدد المحاولات. انتظر قليلًا ثم اطلب رمزًا جديدًا وحاول مجددًا.",
      recovery_unconfigured: "الاستعادة مغلقة. لا تزال أسماء المسؤولين وتفاصيل استعادة البريد الموثّقة وتجربة إعادة الضبط معلّقة.",
      factor_already_enrolled: "تم إعداد تطبيق المصادقة المصطنع بالفعل. ابدأ تحققًا جديدًا بالتطبيق بدلًا من الإعداد.",
      unavailable: "التحقق من الجلسة غير متاح. يبقى الرمز المدخل هنا لتتمكن من إعادة المحاولة.",
    },
  },
} satisfies Record<Locale, unknown>;

export type StaffSecurityMessage = keyof typeof staffSecurityCopy.en.messages;
