import type { Locale } from "@/lib/i18n";
import type { Role } from "@/lib/permissions/contract";
import type { StaffMenuKey } from "./menu";

export const staffCopy = {
  en: {
    inviteAcceptedFallback: "Your password is saved. Sign in to complete your staff verification.", signOutFailed: "Sign-out could not be completed. Private information is hidden here. Try signing out again.", retrySignOut: "Try signing out again",
    timeZone: "Times shown in Asia/Riyadh (UTC+3).", resultLimit: "Showing up to 50 results. Refine your search to find more.", searchPeople: "Search staff by name or email",
    portal: "Staff portal", private: "MSRC 2027 · Internal access", signIn: "Staff sign-in", inviteOnly: "Staff access is by invitation only.",
    passwordIntro: "Sign in with your staff email and password, then complete your verification step.", email: "Email", password: "Password", name: "Name", next: "Continue", signOut: "Sign out", home: "Staff home", menu: "Your areas", roles: "Roles", soon: "Coming soon", noAreas: "No areas are available for your current roles.",
    accept: "Accept your invitation", acceptIntro: "Set your password, then complete the verification required for your role.", passwordHint: "Use at least 10 characters, up to 72 UTF-8 bytes.", inviteMissing: "This invitation link is incomplete. Ask a Super Admin to resend it.",
    emailStep: "Check your email", emailIntro: "Enter the six-digit code sent to your verified staff email. This check applies to this sign-in session.", emailCode: "Email verification code", requestCode: "Send a new email code", verify: "Verify and continue", codeHint: "Enter six digits. Arabic and Latin digits are accepted.",
    totpStep: "Check your authenticator", totpIntro: "Enter the current six-digit code from your authenticator app.", totpCode: "Authenticator code", enroll: "Set up your authenticator", enrollIntro: "Scan this QR code in your authenticator app, then enter its current code. Keep the setup key private.", startEnroll: "Create authenticator setup", qrAlt: "Authenticator setup QR code. A manual setup key is available below.", manual: "Manual setup key", newChallenge: "Start a new authenticator check",
    recovery: "Super Admin recovery: another Super Admin must reset the affected account or authenticator. A Super Admin cannot reset their own access.", sessionPolicy: "Staff sessions expire after 30 minutes of inactivity or 8 hours from sign-in.",
    people: "People and roles", invite: "Invite a staff member", inviteSend: "Send invitation", inviteHint: "The English invitation link expires after 72 hours and can be used once.", invitations: "Invitations", staff: "Staff members", status: "Status", lastSignIn: "Last sign-in", expires: "Expires", resend: "Resend", revokeInvite: "Revoke invitation", editRoles: "Edit roles", saveRoles: "Save roles", suspend: "Suspend", reactivate: "Reactivate", revokeSessions: "Revoke all sessions", resetAuthenticator: "Reset authenticator", resetAccount: "Reset account access", safeguards: "At least two Super Admins must stay active. Your own Super Admin role and access cannot be removed here.",
    audit: "Audit log", auditIntro: "Immutable activity records. Search by actor, action, target or result.", actor: "Who", action: "Action", target: "To whom", when: "When", result: "Result", searchAudit: "Filter audit records", searchParticipants: "Search name or email", search: "Search", participants: "Participants", created: "Created", identifier: "Identity document", reveal: "Reveal", hide: "Hide", revealHint: "Full identity access is recorded in the audit log.", identityPending: "Registration identity field is not available yet.", noRecords: "No records found.", unknown: "Not recorded", loading: "Checking access…", language: "Language", testMode: "Synthetic local test · No real accounts or email", errors: { required: "Complete the required fields.", code: "Enter a six-digit code.", password: "Use a password of at least 10 characters and no more than 72 UTF-8 bytes." },
    states: { ready: "", authenticated: "", "pending-email": "Password accepted. Complete your email check.", "pending-totp": "Password accepted. Complete your authenticator check.", "enroll-totp": "Set up your authenticator to continue.", closed: "Staff access is closed.", unavailable: "Access could not be verified. Try again.", "invalid-input": "Check your input and try again.", "invalid-credentials": "Sign-in could not be completed. Check your details and try again.", "invalid-code": "The code could not be verified. Use a current code and try again.", denied: "This action is not available to your account.", limited: "Too many attempts. Wait before trying again.", invited: "Invitation sent.", updated: "Change saved.", accepted: "Invitation accepted. Complete your verification step.", "signed-out": "You are signed out." },
    statuses: { active: "Active", suspended: "Suspended", pending: "Pending", accepted: "Accepted", revoked: "Revoked", expired: "Expired", unverified: "Unverified", verified: "Verified" },
    areas: { people: "People and roles", audit: "Audit log", participants: "Participants", registration: "Registration and workshops", finance: "Finance", "check-in": "Check-in", review: "Assigned reviews", science: "Scientific administration", judging: "Judging readiness", "faculty-judging": "Faculty judging", content: "Content and media", sponsorship: "Sponsorship and PR" },
    roleLabels: { participant: "Participant", abstractReviewer: "Abstract reviewer", hackathonReviewer: "Hackathon reviewer", threeMinuteThesisReviewer: "3MT reviewer", scientificAdministrator: "Scientific administrator", judgingCommittee: "Judging committee", facultyJudge: "Faculty judge", registrationWorkshopAdministrator: "Registration / workshop administrator", finance: "Finance", checkInStaff: "Check-in staff", contentMediaEditor: "Content / media editor", sponsorshipPr: "Sponsorship / PR", superAdmin: "Super Admin" },
  },
  ar: {
    inviteAcceptedFallback: "حُفظت كلمة مرورك. سجّل الدخول لإكمال التحقق المطلوب للفريق.", signOutFailed: "تعذّر إكمال تسجيل الخروج. أُخفيت المعلومات الخاصة هنا. حاول تسجيل الخروج مجددًا.", retrySignOut: "محاولة تسجيل الخروج مجددًا",
    timeZone: "الأوقات بتوقيت الرياض (UTC+3).", resultLimit: "تُعرض حتى ٥٠ نتيجة. حدّد بحثك للوصول إلى نتائج أخرى.", searchPeople: "البحث عن أعضاء الفريق بالاسم أو البريد",
    portal: "بوابة الفريق", private: "MSRC 2027 · وصول داخلي", signIn: "تسجيل دخول الفريق", inviteOnly: "الوصول لأعضاء الفريق بدعوة فقط.",
    passwordIntro: "سجّل الدخول ببريد الفريق وكلمة المرور، ثم أكمل خطوة التحقق.", email: "البريد الإلكتروني", password: "كلمة المرور", name: "الاسم", next: "متابعة", signOut: "تسجيل الخروج", home: "الرئيسية للفريق", menu: "مجالات عملك", roles: "الأدوار", soon: "قريبًا", noAreas: "لا توجد مجالات متاحة لأدوارك الحالية.",
    accept: "قبول دعوتك", acceptIntro: "أنشئ كلمة المرور، ثم أكمل التحقق المطلوب لدورك.", passwordHint: "استخدم ١٠ أحرف على الأقل، وبحد أقصى ٧٢ بايت بترميز UTF-8.", inviteMissing: "رابط الدعوة غير مكتمل. اطلب من مشرف أعلى إعادة إرساله.",
    emailStep: "تحقق من بريدك", emailIntro: "أدخل الرمز المكوّن من ستة أرقام المرسل إلى بريد الفريق الموثّق. يخص هذا التحقق جلسة الدخول الحالية.", emailCode: "رمز التحقق من البريد", requestCode: "إرسال رمز بريد جديد", verify: "التحقق والمتابعة", codeHint: "أدخل ستة أرقام. تُقبل الأرقام العربية واللاتينية.",
    totpStep: "تحقق من تطبيق المصادقة", totpIntro: "أدخل الرمز الحالي المكوّن من ستة أرقام من تطبيق المصادقة.", totpCode: "رمز تطبيق المصادقة", enroll: "إعداد تطبيق المصادقة", enrollIntro: "امسح رمز QR في تطبيق المصادقة، ثم أدخل الرمز الحالي. حافظ على سرية مفتاح الإعداد.", startEnroll: "إنشاء إعداد تطبيق المصادقة", qrAlt: "رمز QR لإعداد تطبيق المصادقة. يتوفر مفتاح الإعداد اليدوي أدناه.", manual: "مفتاح الإعداد اليدوي", newChallenge: "بدء تحقق جديد بتطبيق المصادقة",
    recovery: "استعادة وصول المشرف الأعلى: يجب أن يعيد مشرف أعلى آخر ضبط الحساب المتأثر أو تطبيق المصادقة. لا يمكن للمشرف الأعلى إعادة ضبط وصوله بنفسه.", sessionPolicy: "تنتهي جلسات الفريق بعد ٣٠ دقيقة من الخمول أو ٨ ساعات من تسجيل الدخول.",
    people: "الأشخاص والأدوار", invite: "دعوة عضو للفريق", inviteSend: "إرسال الدعوة", inviteHint: "تنتهي صلاحية رابط الدعوة باللغة الإنجليزية بعد ٧٢ ساعة ويمكن استخدامه مرة واحدة.", invitations: "الدعوات", staff: "أعضاء الفريق", status: "الحالة", lastSignIn: "آخر تسجيل دخول", expires: "انتهاء الصلاحية", resend: "إعادة الإرسال", revokeInvite: "إلغاء الدعوة", editRoles: "تعديل الأدوار", saveRoles: "حفظ الأدوار", suspend: "تعليق", reactivate: "إعادة التفعيل", revokeSessions: "إلغاء جميع الجلسات", resetAuthenticator: "إعادة ضبط تطبيق المصادقة", resetAccount: "إعادة ضبط الوصول للحساب", safeguards: "يجب أن يظل مشرفان أعلى على الأقل نشطين. لا يمكن إزالة دورك كمشرف أعلى أو وصولك من هنا.",
    audit: "سجل التدقيق", auditIntro: "سجلات نشاط ثابتة. ابحث حسب الشخص أو الإجراء أو المستهدف أو النتيجة.", actor: "من", action: "الإجراء", target: "لمن", when: "الوقت", result: "النتيجة", searchAudit: "تصفية سجلات التدقيق", searchParticipants: "البحث بالاسم أو البريد", search: "بحث", participants: "المشاركون", created: "تاريخ الإنشاء", identifier: "وثيقة الهوية", reveal: "إظهار", hide: "إخفاء", revealHint: "يُسجل الوصول للهوية الكاملة في سجل التدقيق.", identityPending: "حقل هوية التسجيل غير متاح بعد.", noRecords: "لم تُعثر على سجلات.", unknown: "غير مسجل", loading: "جارٍ التحقق من الوصول…", language: "اللغة", testMode: "اختبار محلي ببيانات مصطنعة · لا حسابات أو بريد فعلي", errors: { required: "أكمل الحقول المطلوبة.", code: "أدخل رمزًا مكوّنًا من ستة أرقام.", password: "استخدم كلمة مرور من ١٠ أحرف على الأقل وبحد أقصى ٧٢ بايت بترميز UTF-8." },
    states: { ready: "", authenticated: "", "pending-email": "قُبلت كلمة المرور. أكمل تحقق البريد.", "pending-totp": "قُبلت كلمة المرور. أكمل تحقق تطبيق المصادقة.", "enroll-totp": "أعدّ تطبيق المصادقة للمتابعة.", closed: "الوصول للفريق مغلق.", unavailable: "تعذّر التحقق من الوصول. حاول مجددًا.", "invalid-input": "راجع مدخلاتك وحاول مجددًا.", "invalid-credentials": "تعذّر تسجيل الدخول. راجع بياناتك وحاول مجددًا.", "invalid-code": "تعذّر التحقق من الرمز. استخدم رمزًا حاليًا وحاول مجددًا.", denied: "هذا الإجراء غير متاح لحسابك.", limited: "محاولات كثيرة. انتظر قبل المحاولة مجددًا.", invited: "أُرسلت الدعوة.", updated: "حُفظ التغيير.", accepted: "قُبلت الدعوة. أكمل خطوة التحقق.", "signed-out": "سُجل خروجك." },
    statuses: { active: "نشط", suspended: "معلّق", pending: "قيد الانتظار", accepted: "مقبولة", revoked: "ملغاة", expired: "منتهية", unverified: "غير موثّق", verified: "موثّق" },
    areas: { people: "الأشخاص والأدوار", audit: "سجل التدقيق", participants: "المشاركون", registration: "التسجيل وورش العمل", finance: "المالية", "check-in": "تسجيل الحضور", review: "المراجعات المسندة", science: "الإدارة العلمية", judging: "جاهزية التحكيم", "faculty-judging": "تحكيم أعضاء هيئة التدريس", content: "المحتوى والوسائط", sponsorship: "الرعاية والعلاقات العامة" },
    roleLabels: { participant: "مشارك", abstractReviewer: "مراجع الملخصات", hackathonReviewer: "مراجع الهاكاثون", threeMinuteThesisReviewer: "مراجع 3MT", scientificAdministrator: "مشرف علمي", judgingCommittee: "لجنة التحكيم", facultyJudge: "محكّم من هيئة التدريس", registrationWorkshopAdministrator: "مشرف التسجيل وورش العمل", finance: "المالية", checkInStaff: "فريق تسجيل الحضور", contentMediaEditor: "محرر المحتوى والوسائط", sponsorshipPr: "الرعاية والعلاقات العامة", superAdmin: "مشرف أعلى" },
  },
} satisfies Record<Locale, { areas: Record<StaffMenuKey, string>; roleLabels: Record<Role, string>; [key: string]: unknown }>;
