import type { Locale } from "@/lib/i18n";

export const participantScreens = ["sign-up", "sign-in", "verify-email", "forgot-password", "reset-password", "my-msrc"] as const;
export type ParticipantScreen = (typeof participantScreens)[number];

export const participantCopy = {
  en: {
    eyebrow: "MSRC 2027 · Your account",
    titles: { "sign-up": "Create your account", "sign-in": "Welcome back", "verify-email": "Verify your email", "forgot-password": "Forgot your password?", "reset-password": "Reset your password", "my-msrc": "My MSRC" },
    leads: {
      "sign-up": "One account for your MSRC journey. Creating an account does not register you for the conference.",
      "sign-in": "Sign in to your MSRC account with your email and password.",
      "verify-email": "Enter the latest six-digit code sent to your email.",
      "forgot-password": "Enter your email to request a password reset code.",
      "reset-password": "Enter the latest reset code and choose a new password.",
      "my-msrc": "Your account details and conference registration status.",
    },
    comingSoon: "Accounts are coming soon",
    closed: "Participant accounts are not open yet. You can continue exploring the conference.",
    registrationClosed: "Registration not open yet",
    explore: "Explore MSRC",
    name: "Name", email: "Email", password: "Password", newPassword: "New password", code: "Six-digit email code",
    ageConfirmed: "I confirm I am 18 or older.", ageRequired: "You must be 18 or older to create an account.",
    codeHint: "Paste or enter the latest code. Arabic and Latin digits are accepted.",
    passwordHint: "Use at least 10 characters and no more than 72 UTF-8 bytes. Arabic characters and emoji use more bytes. Choose a password you do not use for another account.",
    create: "Create account", signIn: "Sign in", verify: "Verify email", requestReset: "Send reset code", reset: "Reset password", resend: "Send a new code", signOut: "Sign out", retry: "Try again",
    checking: "Checking account availability…", pending: "Please wait…",
    privacy: "Privacy notice", privacyVersion: "Notice version", privacyLink: "Read the Privacy notice",
    privacyPending: "The Privacy notice is unavailable. Please try again later.",
    accountState: "Account state", verifiedState: "Email verified", profileName: "Profile name",
    needSignIn: "Sign in with your verified account to view My MSRC.",
    links: { "sign-up": "Create an account", "sign-in": "Sign in", "verify-email": "Verify email", "forgot-password": "Forgot password", "reset-password": "Use a reset code", "my-msrc": "My MSRC" },
    navigation: "Account navigation", errorsTitle: "Please check your details",
    required: "Complete this field.", invalidEmail: "Enter a valid email address.", invalidCode: "Enter a six-digit code.", invalidPassword: "Use a password with at least 10 characters.", passwordTooLong: "Use a password of no more than 72 UTF-8 bytes.", invalidField: "Check this field and try again.", tooLong: "Shorten this value and try again.",
    states: {
      accepted: "If this email can receive the requested code, an email will arrive shortly. Use the latest code.",
      authenticated: "You are signed in.", verified: "Your email is verified. Sign in to continue.", password_reset: "Your password has been reset. Sign in with your new password.", signed_out: "You are signed out.",
      invalid_input: "Check the highlighted fields and try again.", invalid_credentials: "We could not sign you in. Check your email and password and try again.", invalid_code: "The code could not be verified. Check the latest code or request a new one.",
      limited: "Please wait before trying again. You can request a new code when the wait ends.", unavailable: "Accounts are temporarily unavailable. Your entered details are still here; please try again.",
      closed: "Participant accounts are not open yet.", ready: "",
    },
    waitUntil: "You can request another code after", expiresAt: "Code expires at", expired: "This code has expired. Request a new code to continue.",
  },
  ar: {
    eyebrow: "MSRC ٢٠٢٧ · حسابك",
    titles: { "sign-up": "أنشئ حسابك", "sign-in": "أهلًا بعودتك", "verify-email": "تحقق من بريدك الإلكتروني", "forgot-password": "نسيت كلمة المرور؟", "reset-password": "أعد تعيين كلمة المرور", "my-msrc": "حسابي في MSRC" },
    leads: {
      "sign-up": "حساب واحد لرحلتك في المؤتمر. إنشاء الحساب لا يعني التسجيل لحضور المؤتمر.",
      "sign-in": "ادخل إلى حسابك باستخدام بريدك الإلكتروني وكلمة المرور.",
      "verify-email": "أدخل أحدث رمز مكوّن من ستة أرقام أُرسل إلى بريدك الإلكتروني.",
      "forgot-password": "أدخل بريدك الإلكتروني لطلب رمز إعادة تعيين كلمة المرور.",
      "reset-password": "أدخل أحدث رمز لإعادة التعيين واختر كلمة مرور جديدة.",
      "my-msrc": "تفاصيل حسابك وحالة التسجيل في المؤتمر.",
    },
    comingSoon: "حسابات المشاركين قريبًا",
    closed: "لم تُفتح حسابات المشاركين بعد. يمكنك متابعة استكشاف المؤتمر.",
    registrationClosed: "لم يُفتح التسجيل بعد",
    explore: "اكتشف المؤتمر",
    name: "الاسم", email: "البريد الإلكتروني", password: "كلمة المرور", newPassword: "كلمة المرور الجديدة", code: "رمز البريد المكوّن من ستة أرقام",
    ageConfirmed: "أؤكد أن عمري ١٨ عامًا أو أكثر.", ageRequired: "يجب أن يكون عمرك ١٨ عامًا أو أكثر لإنشاء حساب.",
    codeHint: "الصق أحدث رمز أو اكتبه. تُقبل الأرقام العربية واللاتينية.",
    passwordHint: "استخدم كلمة مرور من ١٠ أحرف على الأقل ولا تتجاوز ٧٢ بايت بترميز UTF-8. تستخدم الأحرف العربية والرموز التعبيرية عددًا أكبر من البايتات. اختر كلمة مرور لا تستخدمها في حساب آخر.",
    create: "إنشاء حساب", signIn: "تسجيل الدخول", verify: "التحقق من البريد", requestReset: "إرسال رمز إعادة التعيين", reset: "إعادة تعيين كلمة المرور", resend: "إرسال رمز جديد", signOut: "تسجيل الخروج", retry: "المحاولة مجددًا",
    checking: "جارٍ التحقق من إتاحة الحسابات…", pending: "يرجى الانتظار…",
    privacy: "إشعار الخصوصية", privacyVersion: "إصدار الإشعار", privacyLink: "اقرأ إشعار الخصوصية",
    privacyPending: "إشعار الخصوصية غير متاح حاليًا. يرجى المحاولة لاحقًا.",
    accountState: "حالة الحساب", verifiedState: "تم التحقق من البريد", profileName: "الاسم في الحساب",
    needSignIn: "سجّل الدخول بحسابك الموثّق لعرض حسابك في المؤتمر.",
    links: { "sign-up": "إنشاء حساب", "sign-in": "تسجيل الدخول", "verify-email": "التحقق من البريد", "forgot-password": "نسيت كلمة المرور", "reset-password": "استخدام رمز إعادة التعيين", "my-msrc": "حسابي في MSRC" },
    navigation: "التنقل بين صفحات الحساب", errorsTitle: "يرجى التحقق من بياناتك",
    required: "أكمل هذا الحقل.", invalidEmail: "أدخل عنوان بريد إلكتروني صحيحًا.", invalidCode: "أدخل رمزًا مكوّنًا من ستة أرقام.", invalidPassword: "استخدم كلمة مرور من ١٠ أحرف على الأقل.", passwordTooLong: "استخدم كلمة مرور لا تتجاوز ٧٢ بايت بترميز UTF-8.", invalidField: "تحقق من هذا الحقل وحاول مجددًا.", tooLong: "اختصر هذا النص وحاول مجددًا.",
    states: {
      accepted: "إذا كان هذا البريد يمكنه استلام الرمز المطلوب، فستصله رسالة قريبًا. استخدم أحدث رمز.",
      authenticated: "تم تسجيل دخولك.", verified: "تم التحقق من بريدك. سجّل الدخول للمتابعة.", password_reset: "أُعيد تعيين كلمة المرور. سجّل الدخول بكلمة المرور الجديدة.", signed_out: "تم تسجيل خروجك.",
      invalid_input: "تحقق من الحقول الموضّحة وحاول مجددًا.", invalid_credentials: "تعذر تسجيل الدخول. تحقق من بريدك وكلمة المرور وحاول مجددًا.", invalid_code: "تعذر التحقق من الرمز. تحقق من أحدث رمز أو اطلب رمزًا جديدًا.",
      limited: "يرجى الانتظار قبل المحاولة مجددًا. يمكنك طلب رمز جديد بعد انتهاء الانتظار.", unavailable: "الحسابات غير متاحة مؤقتًا. لا تزال بياناتك المدخلة هنا؛ يرجى المحاولة مجددًا.",
      closed: "لم تُفتح حسابات المشاركين بعد.", ready: "",
    },
    waitUntil: "يمكنك طلب رمز جديد بعد", expiresAt: "تنتهي صلاحية الرمز عند", expired: "انتهت صلاحية هذا الرمز. اطلب رمزًا جديدًا للمتابعة.",
  },
} as const satisfies Record<Locale, unknown>;
