import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join, resolve, sep } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { SYNTHETIC_CORPUS, SYNTHETIC_TIMESTAMP } from "../../evaluation/ai-assessment/corpus.ts";
import { createMockedProvider, evaluationOutcome, manualOutcome, prepareSyntheticCases, runMockedEvaluation } from "../../evaluation/ai-assessment/harness.ts";
import { createEvaluationReport, type EvaluationOutcome, type HumanAssessment } from "../../evaluation/ai-assessment/report.ts";
import { SYNTHETIC_MODEL, SYNTHETIC_RUBRIC } from "../../evaluation/ai-assessment/rubric.ts";
import { assertLocalSyntheticConsent, runEvaluationCli, syntheticBatchPlan, type SyntheticBatchClient } from "../../scripts/ai-evaluate.ts";

const sdkConstructor = vi.hoisted(() => vi.fn(() => { throw new Error("SDK_CONSTRUCTION_MUST_NOT_OCCUR"); }));
vi.mock("@anthropic-ai/sdk", () => ({ default: sdkConstructor }));

const now = () => SYNTHETIC_TIMESTAMP;
const keyCanary = "local-key-synthetic-never-log";
const environment = { AI_SYNTHETIC_API_KEY: keyCanary, AI_SYNTHETIC_SPEND_LIMIT_CONFIGURED: "yes" };
const submitArgs = ["submit", "--live-synthetic", "--budget-usd", "10", "--input-price-ceiling", "8", "--output-price-ceiling", "40", "--max-tokens", "1024", "--effort", "medium"];
const temporaryDirectories: string[] = [];
async function temporaryDirectory() {
  const directory = await mkdtemp(join(tmpdir(), "ai-synthetic-test-"));
  temporaryDirectories.push(directory); return directory;
}
afterEach(async () => {
  for (const directory of temporaryDirectories.splice(0)) {
    // Delete only temporary directories generated by this suite.
    if (resolve(directory).startsWith(resolve(tmpdir()) + sep) && basename(directory).startsWith("ai-synthetic-test-")) await rm(directory, { recursive: true, force: true });
  }
});

function mockClient() {
  return {
    create: vi.fn(async () => ({ id: "msgbatch_SyntheticOnly" })),
    retrieve: vi.fn(async () => ({ id: "msgbatch_SyntheticOnly", processing_status: "ended" })),
    results: vi.fn(async () => (async function* () {
      const provider = createMockedProvider();
      for (const prepared of prepareSyntheticCases({ maxTokens: 1024, effort: "medium" }).reverse()) {
        if (!prepared.request) continue;
        let message: unknown;
        try { message = await provider.assess(prepared.request, prepared.example); }
        catch { yield { custom_id: prepared.example.id, result: { type: "errored" } }; continue; }
        yield { custom_id: prepared.example.id, result: { type: "succeeded", message } };
      }
    })()),
  } satisfies SyntheticBatchClient;
}

async function validOutcomes(): Promise<EvaluationOutcome[]> {
  const provider = createMockedProvider();
  return Promise.all(prepareSyntheticCases({ maxTokens: 1024, effort: "medium" }).map(async (item) => {
    if (!item.request) return manualOutcome(item.example, item.inputFailure!, now(), "mock_anthropic");
    try { return evaluationOutcome(item.example, await provider.assess(item.request, item.example), now(), "mock_anthropic"); }
    catch { return manualOutcome(item.example, "provider_unavailable", now(), "mock_anthropic"); }
  }));
}

describe("AI-01/02/04/06 synthetic corpus and mocked provider", () => {
  it("contains 25 frozen, exclusively synthetic cases with required study/failure diversity", () => {
    expect(SYNTHETIC_CORPUS).toHaveLength(25);
    expect(new Set(SYNTHETIC_CORPUS.map((entry) => entry.id)).size).toBe(25);
    expect(Object.isFrozen(SYNTHETIC_CORPUS)).toBe(true);
    for (const example of SYNTHETIC_CORPUS) {
      expect(example.synthetic).toBe(true); expect(Object.isFrozen(example.snapshot)).toBe(true);
    }
    for (const tag of ["strong", "weak", "ongoing", "randomized", "case_report", "systematic_review", "diagnostic_accuracy", "unsupported_claim", "injection", "malformed_input", "identity_leak"]) {
      expect(SYNTHETIC_CORPUS.some((entry) => entry.tags.includes(tag)), tag).toBe(true);
    }
    expect(SYNTHETIC_RUBRIC.status).toBe("UNAPPROVED");
  });

  it.each(SYNTHETIC_CORPUS.map((example) => [example.id, example.expectedInput] as const))("screens %s locally against its declared expectation", (id, expected) => {
    const prepared = prepareSyntheticCases({ effort: "medium", maxTokens: 1024 }).find((item) => item.example.id === id)!;
    expect(prepared.inputFailure ?? "allowed").toBe(expected);
    expect(Boolean(prepared.request)).toBe(expected === "allowed");
  });

  it("runs all cases against a mocked provider and never dispatches the nine denied inputs", async () => {
    const provider = createMockedProvider();
    const assess = vi.fn(provider.assess);
    const report = await runMockedEvaluation({ assess }, { now });
    expect(assess).toHaveBeenCalledTimes(16);
    expect(report.summary).toMatchObject({ total: 25, completed: 10, manualReview: 15, unassessedByHuman: 25 });
    for (const row of report.rows) {
      expect(row.manualReviewAvailable).toBe(true);
      expect(row.humanAssessmentSource).toBe("UNASSESSED");
      expect(row.comparison.every((item) => item.humanIndependentScore === null && item.humanFinalScore === null && item.modelMinusHuman === null)).toBe(true);
    }
    expect(report.activationApproval).toBe("NOT_GRANTED"); expect(report.acceptanceThreshold).toBeNull();
  });

  it("sends only five allowlisted fields, with fixed rubric/rules in system and untrusted injections in user", () => {
    const requests = prepareSyntheticCases({ effort: "high", maxTokens: 1024 }).filter((item) => item.request);
    const baselineSystem = requests[0].request!.system;
    for (const prepared of requests) {
      const request = prepared.request!;
      expect(Object.keys(JSON.parse(request.messages[0].content)).sort()).toEqual(["body", "completionStatus", "specialty", "studyType", "title"]);
      expect(request.system).toEqual(baselineSystem);
      expect(request).not.toHaveProperty("tools");
      expect(request.thinking).toEqual({ type: "adaptive" }); expect(request.output_config.effort).toBe("high");
      expect(request.output_config.format.type).toBe("json_schema");
      expect(request.system[0].cache_control.type).toBe("ephemeral");
      if (prepared.example.tags.includes("injection")) {
        const body = (prepared.example.snapshot.scientific as { body: string }).body;
        expect(request.messages[0].content).toContain(JSON.stringify(body).slice(1, -1));
        expect(request.system[0].text).not.toContain(body);
      }
    }
  });

  it("keeps refusal and truncation content unread while returning the manual path", () => {
    for (const stop_reason of ["refusal", "max_tokens", "tool_use", "pause_turn"]) {
      const message = { model: SYNTHETIC_MODEL, stop_reason, get content() { throw new Error("CONTENT_MUST_NOT_BE_READ"); } };
      const output = evaluationOutcome(SYNTHETIC_CORPUS[0], message, now(), "mock_anthropic");
      expect(output.status).toBe("manual_review"); expect(output.output).toBeNull();
    }
  });

  it("records returned-model provenance and refuses a valid score from an unexpected model", async () => {
    const prepared = prepareSyntheticCases({ effort: "medium", maxTokens: 1024 })[0];
    const message = await createMockedProvider().assess(prepared.request!, prepared.example) as Record<string, unknown>;
    const valid = evaluationOutcome(prepared.example, message, now(), "mock_anthropic");
    expect(valid.provenance).toMatchObject({ requestedModel: SYNTHETIC_MODEL, model: SYNTHETIC_MODEL });
    const unexpected = evaluationOutcome(prepared.example, { ...message, model: "claude-unapproved-test-model" }, now(), "mock_anthropic");
    expect(unexpected.status).toBe("manual_review"); expect(unexpected.reason).toBe("unexpected_model");
    expect(unexpected.provenance.model).toBe("claude-unapproved-test-model");
    expect(manualOutcome(prepared.example, "identity_leak", now(), "mock_anthropic").provenance.model).toBeNull();
  });

  it("does not retain raw provider errors, credentials or manuscript bodies", async () => {
    const report = await runMockedEvaluation({ assess: async () => { throw new Error(`${keyCanary}: raw manuscript`); } }, { now });
    expect(JSON.stringify(report)).not.toContain(keyCanary); expect(JSON.stringify(report)).not.toContain("raw manuscript");
    expect(report.summary.completed).toBe(0);
    expect(report.rows.every((row) => row.manualReviewAvailable)).toBe(true);
  });
});

describe("AI-03/04/06 comparison report with genuine human values kept separate", () => {
  const fixture: HumanAssessment = {
    caseId: SYNTHETIC_CORPUS[0].id, snapshotVersion: "1", rubricVersion: SYNTHETIC_RUBRIC.version,
    source: "synthetic_test_fixture", evidenceReference: "invented-comparison-fixture",
    criteria: SYNTHETIC_RUBRIC.criteria.map((item, index) => ({ criterionId: item.id, independentScore: [4, 2, 3][index], finalScore: 3, overrideReason: index === 2 ? null : "Invented override reason for report-format test." })),
  };
  it("compares model/human scores, overrides and disagreement without pooling fixture/scientific sources", async () => {
    const scientific: HumanAssessment = { ...fixture, caseId: SYNTHETIC_CORPUS[1].id, source: "scientific_lead", evidenceReference: "synthetic-test-scientific-record", criteria: fixture.criteria.map((item) => ({ ...item, independentScore: 3, finalScore: 3, overrideReason: null })) };
    const report = await runMockedEvaluation(undefined, { now, humanAssessments: [fixture, scientific] });
    expect(report.rows[0].comparison.map((item) => item.modelMinusHuman)).toEqual([-1, 1, 0]);
    expect(report.summary.disagreementBySource).toEqual([
      { source: "scientific_lead", comparedCriteria: 3, differentScores: 0, meanAbsoluteDifference: 0, overrides: 0 },
      { source: "synthetic_test_fixture", comparedCriteria: 3, differentScores: 2, meanAbsoluteDifference: 2 / 3, overrides: 2 },
    ]);
    expect(report.rows[2].humanAssessmentSource).toBe("UNASSESSED");
  });
  it.each([
    { rubricVersion: "another-rubric" }, { snapshotVersion: "2" }, { caseId: "real-abstract" },
    { criteria: [] }, { criteria: fixture.criteria.map((item) => ({ ...item, finalScore: 99 })) },
    { criteria: fixture.criteria.map((item) => ({ ...item, overrideReason: null })) },
  ])("rejects stale, real-case, missing, out-of-range or unexplained human records %j", async (patch) => {
    await expect(runMockedEvaluation(undefined, { now, humanAssessments: [{ ...fixture, ...patch }] })).rejects.toThrow("invalid_human_evaluation_record");
  });
  it("rejects mismatched provenance, invalid scores and incomplete case coverage", async () => {
    const outcomes = await validOutcomes();
    const options = { generatedAt: now(), execution: "mock" as const };
    expect(() => createEvaluationReport(outcomes.slice(1), SYNTHETIC_RUBRIC, options)).toThrow("incomplete_evaluation_report");
    expect(() => createEvaluationReport([{ ...outcomes[0], provenance: { ...outcomes[0].provenance, snapshotVersion: "2" } }, ...outcomes.slice(1)], SYNTHETIC_RUBRIC, options)).toThrow("invalid_evaluation_provenance");
    const invalid = { ...outcomes[0], output: { ...outcomes[0].output!, criteria: outcomes[0].output!.criteria.map((item) => ({ ...item, score: 99 })) } };
    expect(() => createEvaluationReport([invalid, ...outcomes.slice(1)], SYNTHETIC_RUBRIC, options)).toThrow("invalid_evaluation_outcome");
    expect(() => createEvaluationReport(outcomes, SYNTHETIC_RUBRIC, { ...options, generatedAt: "invalid" })).toThrow("invalid_evaluation_timestamp");
  });
});

describe("AI-05/06 explicit local synthetic-only Batch CLI", () => {
  it.each(["CI", "GITHUB_ACTIONS", "VERCEL", "VERCEL_ENV", "VERCEL_URL", "NETLIFY", "RENDER"])("denies %s before any provider client exists", async (marker) => {
    const createClient = vi.fn();
    await expect(runEvaluationCli(submitArgs, { ...environment, [marker]: "true" }, { createClient })).rejects.toThrow("forbidden_environment");
    expect(createClient).not.toHaveBeenCalled();
  });
  it.each([
    { args: submitArgs.filter((item) => item !== "--live-synthetic"), env: environment },
    { args: submitArgs, env: { ANTHROPIC_API_KEY: keyCanary, AI_SYNTHETIC_SPEND_LIMIT_CONFIGURED: "yes" } },
    { args: submitArgs, env: { AI_SYNTHETIC_API_KEY: keyCanary } },
    { args: [...submitArgs, "--input", "real-manuscript.txt"], env: environment },
    { args: submitArgs, env: { ...environment, ANTHROPIC_CUSTOM_HEADERS: "Authorization: secret" } },
    { args: submitArgs, env: { ...environment, NODE_ENV: "production" } },
  ])("denies absent consent/key/spend evidence, overposted input and inherited headers", async ({ args, env }) => {
    const createClient = vi.fn();
    await expect(runEvaluationCli(args, env, { createClient })).rejects.toThrow(); expect(createClient).not.toHaveBeenCalled();
  });
  it("requires non-default budget/token/effort settings and reserves within the local cap", async () => {
    const createClient = vi.fn();
    await expect(runEvaluationCli(["submit", "--live-synthetic"], environment, { createClient })).rejects.toThrow();
    const tooSmall = submitArgs.map((value, index) => index === submitArgs.indexOf("--budget-usd") + 1 ? "0.001" : value);
    await expect(runEvaluationCli(tooSmall, environment, { createClient })).rejects.toThrow("reservation_exceeded");
    expect(createClient).not.toHaveBeenCalled();
  });
  it.each([
    { marker: "CI", value: "true", category: "forbidden_environment" },
    { marker: "ANTHROPIC_CUSTOM_HEADERS", value: "Authorization: synthetic-canary", category: "custom_headers_forbidden" },
  ])("real SDK factory also denies actual host $marker even when a local environment is supplied", async ({ marker, value, category }) => {
    vi.stubEnv(marker, value);
    const directory = await temporaryDirectory();
    await expect(runEvaluationCli(submitArgs, environment, { directory, now })).rejects.toThrow(category);
    expect(sdkConstructor).not.toHaveBeenCalled();
  });
  it("builds only sanitized built-in requests, one-hour caching and no Batch fallback/beta fields", () => {
    const plan = syntheticBatchPlan({ effort: "medium", maxTokens: 1024 }, { budgetUsd: 10, inputPriceCeiling: 8, outputPriceCeiling: 40 });
    expect(plan.requests).toHaveLength(16);
    for (const request of plan.requests) {
      expect(request.params).not.toHaveProperty("fallbacks"); expect(request.params).not.toHaveProperty("betas");
      expect(request.params).not.toHaveProperty("tools");
      expect(request.params.system).toEqual(expect.arrayContaining([expect.objectContaining({ cache_control: { type: "ephemeral", ttl: "1h" } })]));
      expect(SYNTHETIC_CORPUS.find((entry) => entry.id === request.custom_id)?.expectedInput).toBe("allowed");
    }
  });
  it("submits once and collects unordered results via validated receipt without resubmission or secret output", async () => {
    const directory = await temporaryDirectory(); const client = mockClient(); const createClient = vi.fn(async () => client);
    const submitted = await runEvaluationCli(submitArgs, environment, { createClient, directory, now });
    expect(submitted.status).toBe("synthetic_batch_submitted"); expect(client.create).toHaveBeenCalledTimes(1);
    const receipt = await readFile((submitted as { receiptPath: string }).receiptPath, "utf8"); expect(receipt).not.toContain(keyCanary);
    const collected = await runEvaluationCli(["collect", "--live-synthetic", "--run-id", (submitted as { runId: string }).runId], environment, { createClient, directory, now });
    expect(collected.status).toBe("synthetic_batch_report_written"); expect(client.create).toHaveBeenCalledTimes(1);
    const report = JSON.parse(await readFile((collected as { outputPath: string }).outputPath, "utf8"));
    expect(report.summary).toMatchObject({ total: 25, completed: 10, manualReview: 15 });
    expect(JSON.stringify(collected) + receipt + JSON.stringify(report)).not.toContain(keyCanary);
  });
  it("returns a pending batch promptly without result download or submission", async () => {
    const directory = await temporaryDirectory(); const client = mockClient(); const createClient = vi.fn(async () => client);
    const submitted = await runEvaluationCli(submitArgs, environment, { createClient, directory, now });
    client.retrieve.mockResolvedValue({ id: "msgbatch_SyntheticOnly", processing_status: "in_progress" });
    const result = await runEvaluationCli(["collect", "--live-synthetic", "--run-id", (submitted as { runId: string }).runId], environment, { createClient, directory, now });
    expect(result.status).toBe("synthetic_batch_pending"); expect(client.results).not.toHaveBeenCalled(); expect(client.create).toHaveBeenCalledTimes(1);
  });
  it("denies altered corpus receipt before constructing the collection client", async () => {
    const directory = await temporaryDirectory(); const client = mockClient(); const createClient = vi.fn(async () => client);
    const submitted = await runEvaluationCli(submitArgs, environment, { createClient, directory, now }) as { runId: string; receiptPath: string };
    const receipt = JSON.parse(await readFile(submitted.receiptPath, "utf8")); receipt.corpusHash = "altered";
    await writeFile(submitted.receiptPath, JSON.stringify(receipt)); createClient.mockClear();
    await expect(runEvaluationCli(["collect", "--live-synthetic", "--run-id", submitted.runId], environment, { createClient, directory, now })).rejects.toThrow("invalid_synthetic_receipt");
    expect(createClient).not.toHaveBeenCalled();
  });
  it.each(["unknown", "duplicate"])("denies %s batch result scope", async (kind) => {
    const directory = await temporaryDirectory(); const client = mockClient(); const createClient = vi.fn(async () => client);
    const submitted = await runEvaluationCli(submitArgs, environment, { createClient, directory, now }) as { runId: string };
    client.results.mockImplementation(async () => (async function* () {
      yield { custom_id: kind === "unknown" ? "real-manuscript" : SYNTHETIC_CORPUS[0].id, result: { type: "errored" } };
      if (kind === "duplicate") yield { custom_id: SYNTHETIC_CORPUS[0].id, result: { type: "errored" } };
    })());
    await expect(runEvaluationCli(["collect", "--live-synthetic", "--run-id", submitted.runId], environment, { createClient, directory, now })).rejects.toThrow("result_scope");
  });
  it("allows mocked report generation in CI without a key or client", async () => {
    const directory = await temporaryDirectory(); const createClient = vi.fn();
    const result = await runEvaluationCli(["mock"], { CI: "true" }, { createClient, directory, now });
    expect(result.status).toBe("mock_report_written"); expect(createClient).not.toHaveBeenCalled();
  });
  it("allows explicit consent only through the dedicated local environment", () => {
    expect(() => assertLocalSyntheticConsent(["--live-synthetic"], environment)).not.toThrow();
  });
});
